import { env } from 'cloudflare:workers';
type Database={prepare:(sql:string)=>{bind:(...values:unknown[])=>{run:()=>Promise<unknown>}}};
type BookingMail={reference:string;customer_name:string;email:string;tour_slug:string;tour_date:string;quantity:number;total:number;status:string;payment_method:string};
function runtimeValue(key:string){const runtimeEnv=env as unknown as Record<string,unknown>;return String(runtimeEnv[key]??process.env[key]??'').trim()}
const escapeHtml=(value:unknown)=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]!));
const statusLabel:Record<string,string>={pending:'Pendiente',confirmed:'Confirmado',completed:'Completado',cancelled:'Cancelado',cancellation_requested:'Cancelación solicitada'};
function template(order:BookingMail,intro:string){return `<div style="font-family:Arial,sans-serif;color:#092c26;max-width:620px;margin:auto"><h1 style="color:#5E9B3E">Bongo Outdoors</h1><p>${escapeHtml(intro)}</p><table style="width:100%;border-collapse:collapse"><tr><td style="padding:8px;border-bottom:1px solid #ddd">Pedido</td><td style="padding:8px;border-bottom:1px solid #ddd"><b>${escapeHtml(order.reference)}</b></td></tr><tr><td style="padding:8px;border-bottom:1px solid #ddd">Tour</td><td style="padding:8px;border-bottom:1px solid #ddd">${escapeHtml(order.tour_slug.replaceAll('-',' '))}</td></tr><tr><td style="padding:8px;border-bottom:1px solid #ddd">Fecha</td><td style="padding:8px;border-bottom:1px solid #ddd">${escapeHtml(order.tour_date)}</td></tr><tr><td style="padding:8px;border-bottom:1px solid #ddd">Cantidad</td><td style="padding:8px;border-bottom:1px solid #ddd">${order.quantity}</td></tr><tr><td style="padding:8px;border-bottom:1px solid #ddd">Total</td><td style="padding:8px;border-bottom:1px solid #ddd"><b>$${Number(order.total).toFixed(2)}</b></td></tr><tr><td style="padding:8px;border-bottom:1px solid #ddd">Pago</td><td style="padding:8px;border-bottom:1px solid #ddd">Contra entrega / efectivo</td></tr><tr><td style="padding:8px">Estado</td><td style="padding:8px"><b>${escapeHtml(statusLabel[order.status]??order.status)}</b></td></tr></table><p style="color:#55736b">Contacto: +507 6446-7276 · info@bongoutdoors.com</p></div>`}
export async function queueEmail(db:Database,to:string,subject:string,html:string){const now=new Date().toISOString();const created=await db.prepare(`INSERT INTO email_notifications (recipient,subject,body_html,status,created_at) VALUES (?,?,?,'pending',?)`).bind(to,subject,html,now).run() as {meta?:{last_row_id?:number}};const id=created.meta?.last_row_id;const apiKey=runtimeValue('RESEND_API_KEY');if(!apiKey||!id)return{queued:true,sent:false};try{const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{authorization:`Bearer ${apiKey}`,'content-type':'application/json','user-agent':'Bongo-Outdoors/1.0','idempotency-key':`bongo-${id}`},body:JSON.stringify({from:runtimeValue('MAIL_FROM')||'Bongo Outdoors <reservas@bongoutdoors.com>',to:[to],subject,html})});if(!response.ok)throw new Error(`Proveedor de correo: ${response.status}`);await db.prepare(`UPDATE email_notifications SET status='sent',sent_at=? WHERE id=?`).bind(new Date().toISOString(),id).run();return{queued:true,sent:true};}catch(cause){await db.prepare(`UPDATE email_notifications SET status='failed',error=? WHERE id=?`).bind(cause instanceof Error?cause.message:'Error desconocido',id).run();return{queued:true,sent:false};}}
export async function notifyNewBooking(db:Database,order:BookingMail){const admin=runtimeValue('ADMIN_EMAILS').split(',').map(x=>x.trim()).filter(Boolean)[0]||'info@bongoutdoors.com';await Promise.all([queueEmail(db,order.email,`Recibimos tu pedido ${order.reference}`,template(order,`Hola ${order.customer_name}, recibimos tu solicitud y te contactaremos para confirmar disponibilidad.`)),queueEmail(db,admin,`Nuevo pedido ${order.reference}`,template(order,`Se recibió un nuevo pedido de ${order.customer_name} (${order.email}).`))]);}
export async function notifyBookingStatus(db:Database,order:BookingMail){const admin=runtimeValue('ADMIN_EMAILS').split(',').map(x=>x.trim()).filter(Boolean)[0]||'info@bongoutdoors.com';const label=statusLabel[order.status]??order.status;await Promise.all([queueEmail(db,order.email,`Tu pedido ${order.reference}: ${label}`,template(order,`El estado de tu pedido cambió a ${label}.`)),queueEmail(db,admin,`Pedido ${order.reference}: ${label}`,template(order,`El pedido fue actualizado a ${label}.`))]);}
