import { env } from 'cloudflare:workers';
const runtime=()=>env as unknown as Record<string,unknown>;
const base=()=>String(runtime().PAYPAL_MODE||'sandbox')==='live'?'https://api-m.paypal.com':'https://api-m.sandbox.paypal.com';
async function token(){const id=String(runtime().PAYPAL_CLIENT_ID||'');const secret=String(runtime().PAYPAL_CLIENT_SECRET||'');if(!id||!secret)throw new Error('PayPal todavía no está configurado. Agrega las credenciales de PayPal en Cloudflare.');const response=await fetch(`${base()}/v1/oauth2/token`,{method:'POST',headers:{Authorization:`Basic ${btoa(`${id}:${secret}`)}`,'content-type':'application/x-www-form-urlencoded'},body:'grant_type=client_credentials'});const data=await response.json() as {access_token?:string;error_description?:string};if(!response.ok||!data.access_token)throw new Error(data.error_description||'No se pudo conectar con PayPal.');return data.access_token;}
export async function createPayPalOrder(amount:number,returnUrl:string,cancelUrl:string){const access=await token();const response=await fetch(`${base()}/v2/checkout/orders`,{method:'POST',headers:{Authorization:`Bearer ${access}`,'content-type':'application/json'},body:JSON.stringify({intent:'CAPTURE',purchase_units:[{description:'Reserva Bongo Outdoors',amount:{currency_code:'USD',value:amount.toFixed(2)}}],payment_source:{paypal:{experience_context:{brand_name:'Bongo Outdoors Tours',landing_page:'GUEST_CHECKOUT',shipping_preference:'NO_SHIPPING',locale:'es-PA',user_action:'PAY_NOW',return_url:returnUrl,cancel_url:cancelUrl}}}})});const data=await response.json() as {id?:string;links?:Array<{rel:string;href:string}>;message?:string};const url=data.links?.find(link=>link.rel==='payer-action'||link.rel==='approve')?.href;if(!response.ok||!data.id||!url)throw new Error(data.message||'No se pudo iniciar el pago con PayPal.');return{orderId:data.id,url};}
type PayPalOrder={status?:string;id?:string;message?:string;purchase_units?:Array<{payments?:{captures?:Array<{status?:string;amount?:{currency_code?:string;value?:string}}>} }>};
export async function getPayPalOrder(orderId:string){const access=await token();const response=await fetch(`${base()}/v2/checkout/orders/${encodeURIComponent(orderId)}`,{headers:{Authorization:`Bearer ${access}`,'content-type':'application/json'}});const data=await response.json() as PayPalOrder;if(!response.ok)throw new Error(data.message||'No se pudo consultar el pago en PayPal.');return data;}
export async function capturePayPalOrder(orderId:string){const access=await token();const response=await fetch(`${base()}/v2/checkout/orders/${encodeURIComponent(orderId)}/capture`,{method:'POST',headers:{Authorization:`Bearer ${access}`,'content-type':'application/json'}});const data=await response.json() as PayPalOrder;if(response.ok&&data.status==='COMPLETED')return data;const existing=await getPayPalOrder(orderId);if(existing.status==='COMPLETED')return existing;throw new Error(data.message||'PayPal no confirmó el pago.');}
export async function verifyPayPalPayment(orderId:string,expectedTotal:number){const order=await getPayPalOrder(orderId);if(order.status!=='COMPLETED')return false;const captured=(order.purchase_units||[]).flatMap(unit=>unit.payments?.captures||[]).filter(capture=>capture.status==='COMPLETED').reduce((sum,capture)=>sum+Number(capture.amount?.value||0),0);return Math.abs(captured-expectedTotal)<=0.01;}
export async function verifyPayPalWebhookSignature(request:Request,rawBody:string){const webhookId=String(runtime().PAYPAL_WEBHOOK_ID||'');const transmissionId=request.headers.get('paypal-transmission-id');const transmissionTime=request.headers.get('paypal-transmission-time');const transmissionSig=request.headers.get('paypal-transmission-sig');const certUrl=request.headers.get('paypal-cert-url');const authAlgo=request.headers.get('paypal-auth-algo');if(!webhookId||!transmissionId||!transmissionTime||!transmissionSig||!certUrl||!authAlgo)return false;try{const access=await token();const response=await fetch(`${base()}/v1/notifications/verify-webhook-signature`,{method:'POST',headers:{Authorization:`Bearer ${access}`,'content-type':'application/json'},body:JSON.stringify({auth_algo:authAlgo,cert_url:certUrl,transmission_id:transmissionId,transmission_sig:transmissionSig,transmission_time:transmissionTime,webhook_id:webhookId,webhook_event:JSON.parse(rawBody)})});const data=await response.json() as {verification_status?:string};return data.verification_status==='SUCCESS';}catch{return false}}
