import { ensureDatabase } from '../../db/runtime';

export type SiteButton={label:string;url:string;style?:'primary'|'glass'};
export type PageConfig={pageKey:string;eyebrow:string;title:string;description:string;image:string;buttons:SiteButton[];meta:string[]};
const defaults:Record<string,PageConfig>={
  home:{pageKey:'home',eyebrow:'Tours auténticos en Panamá',title:'La aventura empieza donde termina la rutina.',description:'Explora volcanes, islas y bosques con guías locales que conocen cada rincón de Chiriquí.',image:'/images/bongo-hero.png',buttons:[{label:'Explorar tours',url:'#tours',style:'primary'},{label:'Diseña tu aventura',url:'/contacto',style:'glass'}],meta:['08° 46′ N','Chiriquí, Panamá','Desde 2013']},
  tours:{pageKey:'tours',eyebrow:'Explora Panamá',title:'Encuentra tu próxima aventura.',description:'Experiencias pequeñas, guías locales y paisajes que se quedan contigo.',image:'',buttons:[],meta:[]},
  services:{pageKey:'services',eyebrow:'Complementa la aventura',title:'Servicios que hacen el viaje más fácil.',description:'',image:'/images/bongo-hero.png',buttons:[],meta:[]},
  lodgings:{pageKey:'lodgings',eyebrow:'Descansa bien',title:'Hospedajes con alma de aventura.',description:'Opciones claras por persona o para tu grupo completo.',image:'',buttons:[],meta:[]},
  blog:{pageKey:'blog',eyebrow:'Historias de ruta',title:'El cuaderno de Bongo.',description:'Ideas honestas y consejos locales para viajar mejor por Panamá.',image:'',buttons:[],meta:[]},
  faqs:{pageKey:'faqs',eyebrow:'Centro de ayuda',title:'Preguntas frecuentes.',description:'Todo lo que necesitas saber antes de vivir la aventura.',image:'',buttons:[],meta:[]},
};
function json<T>(value:unknown,fallback:T):T{try{return JSON.parse(String(value??'')) as T}catch{return fallback}}
export async function getPageConfig(pageKey:string){const base=defaults[pageKey]??defaults.home;try{const db=await ensureDatabase();const row=await db.prepare('SELECT * FROM site_pages WHERE page_key=?').bind(pageKey).first<Record<string,unknown>>();return row?{pageKey,eyebrow:String(row.eyebrow??base.eyebrow),title:String(row.title??base.title),description:String(row.description??base.description),image:String(row.image??base.image),buttons:json(row.buttons,base.buttons),meta:json(row.meta,base.meta)}:base}catch{return base}}

export type MenuItem={id?:number;parent_id?:number|null;label:string;url:string;position:string;sort_order:number;open_new_tab?:number};
export const defaultMenu:MenuItem[]=[{label:'Inicio',url:'/',position:'main',sort_order:0},{label:'Bongo',url:'#',position:'main',sort_order:1},{label:'Blog',url:'/blog',position:'main',sort_order:2},{label:'FAQs',url:'/faqs',position:'main',sort_order:3},{label:'Contacto',url:'/contacto',position:'main',sort_order:4},{label:'Tours',url:'/tours',position:'bongo',sort_order:0},{label:'Bike tours',url:'/tours?categoria=bike',position:'bongo',sort_order:1},{label:'Shuttle Panamá',url:'/servicios/shuttle-panama',position:'bongo',sort_order:2},{label:'Servicio de drones',url:'/servicios/fotografia-drones',position:'bongo',sort_order:3},{label:'Tours en Pedasí',url:'/tours?destino=pedasi',position:'bongo',sort_order:4},{label:'Hospedaje y cabañas',url:'/hospedajes',position:'bongo',sort_order:5},{label:'Responsabilidad social',url:'/responsabilidad-social',position:'bongo',sort_order:6},{label:'Derechos de autor',url:'/derechos-de-autor',position:'bongo',sort_order:7}];
export async function getMenuItems(){try{const db=await ensureDatabase();const rows=(await db.prepare('SELECT id,parent_id,label,url,position,sort_order,open_new_tab FROM menu_items WHERE active=1 ORDER BY position,sort_order,id').all<MenuItem>()).results;const source=rows.length?rows:defaultMenu;const seen=new Set<string>();return source.filter(item=>{const key=`${item.position}|${item.label.trim().toLowerCase()}|${item.url.trim()}`;if(seen.has(key))return false;seen.add(key);return true})}catch{return defaultMenu}}
const categoryTable:Record<string,string>={tour:'categories',service:'service_categories',lodging:'lodging_categories',post:'post_categories',faq:'faq_categories'};
export async function getModuleCategories(entity:string){const table=categoryTable[entity];if(!table)return[];try{const db=await ensureDatabase();return(await db.prepare(`SELECT * FROM ${table} ORDER BY ${table==='categories'?'name':'sort_order,name'}`).all<Record<string,unknown>>()).results}catch{return[]}}
