import { ensureDatabase } from '../../db/runtime';

export type SiteButton={label:string;url:string;style?:'primary'|'glass'};
export type HeroConfig={type:'image'|'video'|'slideshow';videoUrl?:string;slides?:{url:string;duration:number;kenburns:boolean}[]};
export type HomeSections={tours:{eyebrow:string;title:string};categories:{eyebrow:string;title:string;intro:string};destinations:{eyebrow:string;title:string;intro:string};story:{eyebrow:string;title:string;text:string};reviews:{eyebrow:string;title:string};faq:{eyebrow:string;title:string;text:string}};
export const defaultHomeSections:HomeSections={tours:{eyebrow:'Experiencias inolvidables',title:'Best adventure tours in Chiriquí & Pedasí, Panamá'},categories:{eyebrow:'Encuentra tu plan',title:'Aventuras para tu estilo',intro:'Desde la cima del volcán hasta el azul del Pacífico. Elige cómo quieres vivir Panamá.'},destinations:{eyebrow:'Destinos',title:'Panamá se vive al aire libre.',intro:'Paisajes distintos, una misma energía. Conectamos cada salida con la gente, la cultura y la naturaleza del lugar.'},story:{eyebrow:'Más que un tour',title:'Conocemos el camino. Cuidamos el destino.',text:'Somos una empresa local nacida entre las montañas de Chiriquí. Cada experiencia apoya a guías, comunidades y pequeños negocios de la región.'},reviews:{eyebrow:'Ellos ya lo vivieron',title:'Historias que vuelven con una sonrisa.'},faq:{eyebrow:'Antes de salir',title:'¿Tienes preguntas?',text:'Encuentra respuestas rápidas o escríbenos directamente. Estamos para ayudarte a elegir bien.'}};
export type PageConfig={pageKey:string;eyebrow:string;title:string;description:string;image:string;buttons:SiteButton[];meta:string[];heroConfig:HeroConfig;tourSort:'manual'|'sales'|'reviews';tourOrder:string[];seoTitle:string;seoDescription:string;seoKeywords:string;sections:HomeSections};
const defaults:Record<string,PageConfig>={
  home:{pageKey:'home',eyebrow:'Tours auténticos en Panamá',title:'La aventura empieza donde termina la rutina.',description:'Explora volcanes, islas y bosques con guías locales que conocen cada rincón de Chiriquí.',image:'/images/bongo-hero.png',buttons:[{label:'Explorar tours',url:'#tours',style:'primary'},{label:'Diseña tu aventura',url:'/contacto',style:'glass'}],meta:['08° 46′ N','Chiriquí, Panamá','Desde 2013']},
  tours:{pageKey:'tours',eyebrow:'Explora Panamá',title:'Encuentra tu próxima aventura.',description:'Experiencias pequeñas, guías locales y paisajes que se quedan contigo.',image:'',buttons:[],meta:[]},
  services:{pageKey:'services',eyebrow:'Complementa la aventura',title:'Servicios que hacen el viaje más fácil.',description:'',image:'/images/bongo-hero.png',buttons:[],meta:[]},
  lodgings:{pageKey:'lodgings',eyebrow:'Descansa bien',title:'Hospedajes con alma de aventura.',description:'Opciones claras por persona o para tu grupo completo.',image:'',buttons:[],meta:[]},
  blog:{pageKey:'blog',eyebrow:'Historias de ruta',title:'El cuaderno de Bongo.',description:'Ideas honestas y consejos locales para viajar mejor por Panamá.',image:'',buttons:[],meta:[]},
  faqs:{pageKey:'faqs',eyebrow:'Centro de ayuda',title:'Preguntas frecuentes.',description:'Todo lo que necesitas saber antes de vivir la aventura.',image:'',buttons:[],meta:[]},
};
function json<T>(value:unknown,fallback:T):T{try{return JSON.parse(String(value??'')) as T}catch{return fallback}}
export async function getPageConfig(pageKey:string){const base=defaults[pageKey]??defaults.home;const defaultHero:HeroConfig={type:'image'};const fallback={...base,heroConfig:defaultHero,tourSort:'manual' as const,tourOrder:[] as string[],seoTitle:base.title,seoDescription:base.description,seoKeywords:'',sections:defaultHomeSections};try{const db=await ensureDatabase();const row=await db.prepare('SELECT * FROM site_pages WHERE page_key=?').bind(pageKey).first<Record<string,unknown>>();return row?{pageKey,eyebrow:String(row.eyebrow??base.eyebrow),title:String(row.title??base.title),description:String(row.description??base.description),image:String(row.image??base.image),buttons:json(row.buttons,base.buttons),meta:json(row.meta,base.meta),heroConfig:json<HeroConfig>(row.hero_config,defaultHero),tourSort:(String(row.tour_sort??'manual') as 'manual'|'sales'|'reviews'),tourOrder:json<string[]>(row.tour_order,[]),seoTitle:String(row.seo_title||row.title||base.title),seoDescription:String(row.seo_description||row.description||base.description),seoKeywords:String(row.seo_keywords||''),sections:json<HomeSections>(row.sections,defaultHomeSections)}:fallback}catch{return fallback}}

export type MenuItem={id?:number;parent_id?:number|null;label:string;url:string;position:string;sort_order:number;open_new_tab?:number};
export const defaultMenu:MenuItem[]=[{label:'Inicio',url:'/',position:'main',sort_order:0},{label:'Bongo',url:'#',position:'main',sort_order:1},{label:'Blog',url:'/blog',position:'main',sort_order:2},{label:'FAQs',url:'/faqs',position:'main',sort_order:3},{label:'Contacto',url:'/contacto',position:'main',sort_order:4},{label:'Tours',url:'/tours',position:'bongo',sort_order:0},{label:'Bike tours',url:'/tours?categoria=bike',position:'bongo',sort_order:1},{label:'Shuttle Panamá',url:'/servicios/shuttle-panama',position:'bongo',sort_order:2},{label:'Servicio de drones',url:'/servicios/fotografia-drones',position:'bongo',sort_order:3},{label:'Tours en Pedasí',url:'/tours?destino=pedasi',position:'bongo',sort_order:4},{label:'Hospedaje y cabañas',url:'/hospedajes',position:'bongo',sort_order:5},{label:'Responsabilidad social',url:'/responsabilidad-social',position:'bongo',sort_order:6},{label:'Derechos de autor',url:'/derechos-de-autor',position:'bongo',sort_order:7}];
export async function getMenuItems(){try{const db=await ensureDatabase();const rows=(await db.prepare('SELECT id,parent_id,label,url,position,sort_order,open_new_tab FROM menu_items WHERE active=1 ORDER BY position,sort_order,id').all<MenuItem>()).results;const source=rows.length?rows:defaultMenu;const seen=new Set<string>();const unique=source.filter(item=>{const key=`${item.position}|${item.label.trim().toLowerCase()}|${item.url.trim()}`;if(seen.has(key))return false;seen.add(key);return true});const withIds=unique.map((item,index)=>({...item,id:item.id??(100000+index)}));const bongoParent=withIds.find(item=>item.position==='main'&&item.label.trim().toLowerCase()==='bongo');return withIds.map(item=>({...item,parent_id:item.parent_id??(item.position==='bongo'&&bongoParent?bongoParent.id:null)}))}catch{return defaultMenu.map((item,index)=>({...item,id:100000+index,parent_id:null}))}}
const categoryTable:Record<string,string>={tour:'categories',service:'service_categories',lodging:'lodging_categories',post:'post_categories',faq:'faq_categories'};
export async function getModuleCategories(entity:string){const table=categoryTable[entity];if(!table)return[];try{const db=await ensureDatabase();return(await db.prepare(`SELECT * FROM ${table} ORDER BY ${table==='categories'?'name':'sort_order,name'}`).all<Record<string,unknown>>()).results}catch{return[]}}
