import { ensureDatabase } from '../../db/runtime';
import { tours as demos, type PriceType, type Tour } from '../data';

type TourRow={slug:string;name:string;h1:string;location:string;meeting_point:string|null;departure_time:string|null;person_price:number|null;group_price:number|null;price_type:string;season_prices:string|null;duration:string;difficulty:string;capacity:string|null;cover_image:string|null;description:string;meta_description:string|null;policy_content:string|null;category_name:string|null;includes:string|null;not_included:string|null;bring:string|null;prohibited:string|null;recommendations:string|null;extra_messages:string|null};
const lines=(value:string|null)=>value?.split('\n').map(item=>item.trim()).filter(Boolean);
function minimumFromCapacity(capacity:string|null){const match=capacity?.match(/\d+/);return match?Number(match[0]):1}
function rowToTour(row:TourRow):Tour{const priceType:PriceType=row.price_type==='group'?'group':'person';return{slug:row.slug,name:row.name,h1:row.h1,category:row.category_name||'Aventura',location:row.location,meetingPoint:row.meeting_point||undefined,departureTime:row.departure_time||undefined,price:priceType==='group'?(row.group_price??row.person_price??0):(row.person_price??row.group_price??0),priceType,groupPrice:row.group_price??undefined,seasonPrices:row.season_prices??undefined,policy:row.policy_content??undefined,duration:row.duration,difficulty:row.difficulty,difficultyScore:5,capacity:row.capacity??'Consultar',minPeople:minimumFromCapacity(row.capacity),image:row.cover_image||'/images/bongo-hero.png',short:row.meta_description||row.description.slice(0,150),includes:lines(row.includes),notIncluded:lines(row.not_included),bring:lines(row.bring),prohibited:lines(row.prohibited),recommendations:lines(row.recommendations),extraMessages:lines(row.extra_messages)}}
const fields=`t.slug,t.name,t.h1,t.location,t.meeting_point,t.departure_time,t.person_price,t.group_price,t.price_type,t.season_prices,t.duration,t.difficulty,t.capacity,t.cover_image,t.description,t.meta_description,p.content AS policy_content,c.name AS category_name,t.includes,t.not_included,t.bring,t.prohibited,t.recommendations,t.extra_messages`;
export async function getTours(){try{const db=await ensureDatabase();const result=await db.prepare(`SELECT ${fields} FROM tours t LEFT JOIN policies p ON t.policy_id=p.id LEFT JOIN categories c ON t.category_id=c.id WHERE t.status='published' ORDER BY t.id DESC`).all<TourRow>();const custom=result.results.map(rowToTour);return[...custom,...demos.filter(d=>!custom.some(c=>c.slug===d.slug))]}catch{return demos}}
export async function getTour(slug:string){const demo=demos.find(t=>t.slug===slug);try{const db=await ensureDatabase();const row=await db.prepare(`SELECT ${fields.replace('p.content AS policy_content','COALESCE(p.content,g.content) AS policy_content')} FROM tours t LEFT JOIN policies p ON t.policy_id=p.id LEFT JOIN policies g ON g.is_global=1 LEFT JOIN categories c ON t.category_id=c.id WHERE t.slug=? AND t.status='published' ORDER BY g.id DESC LIMIT 1`).bind(slug).first<TourRow>();return row?rowToTour(row):demo}catch{return demo}}
