import { env } from 'cloudflare:workers';import { NextResponse } from 'next/server';import { getChatGPTUser,isAdminEmail } from '../../chatgpt-auth';import { ensureDatabase } from '../../../db/runtime';
async function requireAdmin(){const user=await getChatGPTUser();return Boolean(user&&isAdminEmail(user.email))}
const mediaTypes:Record<string,{extension:string;matches:(bytes:Uint8Array)=>boolean}>={
  'image/jpeg':{extension:'jpg',matches:b=>b[0]===0xff&&b[1]===0xd8&&b[2]===0xff},
  'image/png':{extension:'png',matches:b=>b[0]===0x89&&b[1]===0x50&&b[2]===0x4e&&b[3]===0x47},
  'image/gif':{extension:'gif',matches:b=>String.fromCharCode(...b.slice(0,6))==='GIF87a'||String.fromCharCode(...b.slice(0,6))==='GIF89a'},
  'image/webp':{extension:'webp',matches:b=>String.fromCharCode(...b.slice(0,4))==='RIFF'&&String.fromCharCode(...b.slice(8,12))==='WEBP'},
  'image/avif':{extension:'avif',matches:b=>String.fromCharCode(...b.slice(4,12)).includes('ftypavif')||String.fromCharCode(...b.slice(4,12)).includes('ftypavis')},
  'video/mp4':{extension:'mp4',matches:b=>String.fromCharCode(...b.slice(4,8))==='ftyp'},
  'video/webm':{extension:'webm',matches:b=>b[0]===0x1a&&b[1]===0x45&&b[2]===0xdf&&b[3]===0xa3},
};
export async function POST(request:Request){const user=await getChatGPTUser();if(!user)return NextResponse.json({error:'No autorizado'},{status:401});if(!isAdminEmail(user.email))return NextResponse.json({error:'Acceso de administrador requerido'},{status:403});const data=await request.formData();const file=data.get('file');if(!(file instanceof File))return NextResponse.json({error:'Archivo requerido'},{status:400});const media=mediaTypes[file.type];if(!media)return NextResponse.json({error:'Formato no permitido. Usa JPG, PNG, WebP, GIF, AVIF, MP4 o WebM.'},{status:400});if(file.size>8*1024*1024)return NextResponse.json({error:'El archivo supera 8 MB'},{status:400});const buffer=await file.arrayBuffer();if(!media.matches(new Uint8Array(buffer).slice(0,24)))return NextResponse.json({error:'El contenido del archivo no coincide con su formato.'},{status:400});const base=file.name.toLowerCase().replace(/\.[^.]+$/,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'').slice(0,80)||'archivo';const key=`content/${Date.now()}-${crypto.randomUUID().slice(0,8)}-${base}.${media.extension}`;await env.FILES.put(key,buffer,{httpMetadata:{contentType:file.type}});const db=await ensureDatabase();await db.prepare('INSERT INTO media_meta (key,name,alt,updated_at) VALUES (?,?,?,?)').bind(key,file.name,'',new Date().toISOString()).run();return NextResponse.json({ok:true,url:`/api/files/${key}`});}
export async function GET(request:Request){if(!await requireAdmin())return NextResponse.json({error:'Acceso de administrador requerido.'},{status:403});const cursor=new URL(request.url).searchParams.get('cursor')||undefined;const list:any=await env.FILES.list({prefix:'content/',limit:500,cursor});const db=await ensureDatabase();const metas=await db.prepare('SELECT key,name,alt FROM media_meta').all<{key:string;name:string;alt:string}>();const metaMap=new Map(metas.results.map(m=>[m.key,m]));const files=(list.objects||[]).map((obj:any)=>{const meta=metaMap.get(obj.key);return{key:obj.key,name:meta?.name||(obj.key.split('/').pop()||obj.key),alt:meta?.alt||'',size:obj.size,uploaded:obj.uploaded?new Date(obj.uploaded).toISOString():'',contentType:obj.httpMetadata?.contentType||''}});return NextResponse.json({files,cursor:list.truncated?list.cursor:null});}
export async function DELETE(request:Request){if(!await requireAdmin())return NextResponse.json({error:'Acceso de administrador requerido.'},{status:403});const body=await request.json() as Record<string,unknown>;const keys:any[]=Array.isArray(body.keys)?body.keys:[body.key];if(!keys.length||!keys.every((k:any)=>String(k).startsWith('content/')))return NextResponse.json({error:'Clave inválida.'},{status:400});const db=await ensureDatabase();for(const k of keys){await env.FILES.delete(String(k));await db.prepare('DELETE FROM media_meta WHERE key=?').bind(String(k)).run();}return NextResponse.json({ok:true});}
export async function PATCH(request:Request){if(!await requireAdmin())return NextResponse.json({error:'Acceso de administrador requerido.'},{status:403});const body=await request.json() as Record<string,unknown>;const key=String(body.key??'');const name=String(body.name??'').trim();const alt=String(body.alt??'').trim();if(!key.startsWith('content/'))return NextResponse.json({error:'Clave inválida.'},{status:400});const db=await ensureDatabase();await db.prepare('INSERT INTO media_meta (key,name,alt,updated_at) VALUES (?,?,?,?) ON CONFLICT(key) DO UPDATE SET name=excluded.name,alt=excluded.alt,updated_at=excluded.updated_at').bind(key,name,alt,new Date().toISOString()).run();return NextResponse.json({ok:true});}
