import { NextResponse } from 'next/server';
import { getChatGPTUser,isAdminEmail } from '../../../chatgpt-auth';
import { ensureDatabase } from '../../../../db/runtime';
import { ensureCouponSchema } from '../../../lib/coupons';
async function admin(){const user=await getChatGPTUser();return Boolean(user&&isAdminEmail(user.email))}
const text=(body:Record<string,unknown>,key:string,max=2000)=>String(body[key]??'').trim().slice(0,max);
export async function GET(){if(!await admin())return NextResponse.json({error:'Acceso requerido.'},{status:403});const db=await ensureDatabase();await ensureCouponSchema(db);const result=await db.prepare(`SELECT c.*,COUNT(r.id) AS usage_count,COALESCE(SUM(r.discount_amount),0) AS discount_total FROM coupons c LEFT JOIN coupon_redemptions r ON r.coupon_id=c.id GROUP BY c.id ORDER BY c.id DESC`).all();return NextResponse.json(result.results)}
export async function POST(request:Request){if(!await admin())return NextResponse.json({error:'Acceso requerido.'},{status:403});const body=await request.json() as Record<string,unknown>;const db=await ensureDatabase();await ensureCouponSchema(db);const now=new Date().toISOString();const code=text(body,'code',80).toUpperCase().replace(/\s+/g,'');if(!code)return NextResponse.json({error:'El código es obligatorio.'},{status:400});const values=[code,text(body,'description'),text(body,'discountType',20)||'percentage',Math.max(0,Number(body.amount||0)),Math.max(0,Number(body.minCartTotal||0)),body.maxDiscount?Math.max(0,Number(body.maxDiscount)):null,body.usageLimit?Math.max(1,Number(body.usageLimit)):null,body.usageLimitPerUser?Math.max(1,Number(body.usageLimitPerUser)):null,text(body,'productScope',20)||'all',text(body,'productSlugs'),text(body,'allowedEmails'),text(body,'startAt',40)||null,text(body,'endAt',40)||null,body.active===false?0:1,now,now];try{await db.prepare(`INSERT INTO coupons (code,description,discount_type,amount,min_cart_total,max_discount,usage_limit,usage_limit_per_user,product_scope,product_slugs,allowed_emails,start_at,end_at,active,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(...values).run();return NextResponse.json({ok:true})}catch{return NextResponse.json({error:'El código ya existe o los datos no son válidos.'},{status:400})}}
export async function PUT(request:Request){if(!await admin())return NextResponse.json({error:'Acceso requerido.'},{status:403});const body=await request.json() as Record<string,unknown>;const id=Number(body.id||0);if(!id)return NextResponse.json({error:'Cupón inválido.'},{status:400});const db=await ensureDatabase();await ensureCouponSchema(db);await db.prepare(`UPDATE coupons SET code=?,description=?,discount_type=?,amount=?,min_cart_total=?,max_discount=?,usage_limit=?,usage_limit_per_user=?,product_scope=?,product_slugs=?,allowed_emails=?,start_at=?,end_at=?,active=?,updated_at=? WHERE id=?`).bind(text(body,'code',80).toUpperCase().replace(/\s+/g,''),text(body,'description'),text(body,'discountType',20)||'percentage',Math.max(0,Number(body.amount||0)),Math.max(0,Number(body.minCartTotal||0)),body.maxDiscount?Math.max(0,Number(body.maxDiscount)):null,body.usageLimit?Math.max(1,Number(body.usageLimit)):null,body.usageLimitPerUser?Math.max(1,Number(body.usageLimitPerUser)):null,text(body,'productScope',20)||'all',text(body,'productSlugs'),text(body,'allowedEmails'),text(body,'startAt',40)||null,text(body,'endAt',40)||null,body.active===false?0:1,new Date().toISOString(),id).run();return NextResponse.json({ok:true})}
export async function DELETE(request:Request){if(!await admin())return NextResponse.json({error:'Acceso requerido.'},{status:403});const body=await request.json() as {id?:number};const db=await ensureDatabase();await ensureCouponSchema(db);const used=await db.prepare('SELECT COUNT(*) AS total FROM coupon_redemptions WHERE coupon_id=?').bind(Number(body.id||0)).first() as {total:number}|null;if(Number(used?.total||0)>0){await db.prepare('UPDATE coupons SET active=0,updated_at=? WHERE id=?').bind(new Date().toISOString(),Number(body.id||0)).run();return NextResponse.json({ok:true,archived:true})}await db.prepare('DELETE FROM coupons WHERE id=?').bind(Number(body.id||0)).run();return NextResponse.json({ok:true})}
