import { NextResponse } from 'next/server';
import { getChatGPTUser,isAdminEmail } from '../../../chatgpt-auth';
import { ensureDatabase,slugify } from '../../../../db/runtime';
const categoryTables:Record<string,string>={tour:'categories',service:'service_categories',lodging:'lodging_categories',post:'post_categories',faq:'faq_categories'};
async function admin(){const user=await getChatGPTUser();return Boolean(user&&isAdminEmail(user.email))}
export async function GET(){if(!await admin())return NextResponse.json({error:'Acceso requerido.'},{status:403});const db=await ensureDatabase();const [pages,menu,tour,service,lodging,post,faq]=await Promise.all([db.prepare('SELECT * FROM site_pages ORDER BY page_key').all(),db.prepare('SELECT * FROM menu_items ORDER BY position,sort_order,id').all(),db.prepare('SELECT * FROM categories ORDER BY name').all(),db.prepare('SELECT * FROM service_categories ORDER BY sort_order,name').all(),db.prepare('SELECT * FROM lodging_categories ORDER BY sort_order,name').all(),db.prepare('SELECT * FROM post_categories ORDER BY sort_order,name').all(),db.prepare('SELECT * FROM faq_categories ORDER BY sort_order,name').all()]);const seen=new Set<string>();const menuRows=menu.results as Array<Record<string,unknown>>;const bongoParent=menuRows.find(item=>String(item.position)==='main'&&String(item.label).trim().toLowerCase()==='bongo');const normalizedMenu=menuRows.map(item=>({...item,parent_id:item.parent_id??(String(item.position)==='bongo'&&bongoParent?bongoParent.id:null)}));const uniqueMenu=normalizedMenu.filter(item=>{const key=`${item.position}|${String(item.label).trim().toLowerCase()}|${String(item.url).trim()}`;if(seen.has(key))return false;seen.add(key);return true});return NextResponse.json({pages:pages.results,menu:uniqueMenu,categories:{tour:tour.results,service:service.results,lodging:lodging.results,post:post.results,faq:faq.results}})}
export async function POST(request:Request){if(!await admin())return NextResponse.json({error:'Acceso requerido.'},{status:403});const body=await request.json() as Record<string,unknown>;const db=await ensureDatabase();const resource=String(body.resource??'');
if(resource==='page'){const key=String(body.pageKey??'home');await db.prepare(`INSERT INTO site_pages (page_key,eyebrow,title,description,image,buttons,meta,hero_config,tour_sort,tour_order,seo_title,seo_description,seo_keywords,sections,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(page_key) DO UPDATE SET eyebrow=excluded.eyebrow,title=excluded.title,description=excluded.description,image=excluded.image,buttons=excluded.buttons,meta=excluded.meta,hero_config=excluded.hero_config,tour_sort=excluded.tour_sort,tour_order=excluded.tour_order,seo_title=excluded.seo_title,seo_description=excluded.seo_description,seo_keywords=excluded.seo_keywords,sections=excluded.sections,updated_at=excluded.updated_at`).bind(key,String(body.eyebrow??''),String(body.title??''),String(body.description??''),String(body.image??''),String(body.buttons??'[]'),String(body.meta??'[]'),String(body.heroConfig??'{"type":"image"}'),String(body.tourSort??'manual'),String(body.tourOrder??'[]'),String(body.seoTitle??''),String(body.seoDescription??''),String(body.seoKeywords??''),String(body.sections??'{}'),new Date().toISOString()).run();return NextResponse.json({ok:true});}
if(resource==='menu'){const id=Number(body.id||0);const parentId=body.parentId?Number(body.parentId):null;if(id)await db.prepare('UPDATE menu_items SET label=?,url=?,position=?,parent_id=?,sort_order=?,active=?,open_new_tab=? WHERE id=?').bind(String(body.label??''),String(body.url??'/'),String(body.position??'main'),parentId,Number(body.sortOrder||0),body.active===false?0:1,body.openNewTab?1:0,id).run();else await db.prepare('INSERT INTO menu_items (label,url,position,parent_id,sort_order,active,open_new_tab) VALUES (?,?,?,?,?,1,?)').bind(String(body.label??''),String(body.url??'/'),String(body.position??'main'),parentId,Number(body.sortOrder||0),body.openNewTab?1:0).run();return NextResponse.json({ok:true});}
if(resource==='menu-order'){const items=Array.isArray(body.items)?body.items as Array<{id:number;sort_order:number}>:[];for(const item of items){if(item&&Number(item.id))await db.prepare('UPDATE menu_items SET sort_order=? WHERE id=?').bind(Number(item.sort_order),Number(item.id)).run();}return NextResponse.json({ok:true});}
if(resource==='menu-move'){const id=Number(body.id);const parentId=body.parentId?Number(body.parentId):null;const row=parentId?await db.prepare('SELECT COUNT(*) AS c FROM menu_items WHERE parent_id=?').bind(parentId).first<{c:number}>():await db.prepare('SELECT COUNT(*) AS c FROM menu_items WHERE parent_id IS NULL').first<{c:number}>();await db.prepare('UPDATE menu_items SET parent_id=?,sort_order=? WHERE id=?').bind(parentId,row?.c??0,id).run();return NextResponse.json({ok:true});}
if(resource==='category'){const entity=String(body.entity??'');const table=categoryTables[entity];if(!table)return NextResponse.json({error:'Categoría inválida.'},{status:400});const name=String(body.name??'');const slug=slugify(String(body.slug||name));const id=Number(body.id||0);if(table==='categories'){if(id)await db.prepare('UPDATE categories SET name=?,slug=?,description=? WHERE id=?').bind(name,slug,String(body.description??''),id).run();else await db.prepare('INSERT INTO categories (name,slug,description,created_at) VALUES (?,?,?,?)').bind(name,slug,String(body.description??''),new Date().toISOString()).run();}else if(table==='faq_categories'){if(id)await db.prepare('UPDATE faq_categories SET name=?,sort_order=? WHERE id=?').bind(name,Number(body.sortOrder||0),id).run();else await db.prepare('INSERT INTO faq_categories (name,sort_order) VALUES (?,?)').bind(name,Number(body.sortOrder||0)).run();}else if(id)await db.prepare(`UPDATE ${table} SET name=?,slug=?,description=?,sort_order=?,active=1 WHERE id=?`).bind(name,slug,String(body.description??''),Number(body.sortOrder||0),id).run();else await db.prepare(`INSERT INTO ${table} (name,slug,description,sort_order,active) VALUES (?,?,?,?,1) ON CONFLICT(slug) DO UPDATE SET name=excluded.name,description=excluded.description,active=1`).bind(name,slug,String(body.description??''),Number(body.sortOrder||0)).run();const saved=table==='faq_categories'?null:await db.prepare(`SELECT id FROM ${table} WHERE slug=?`).bind(slug).first<{id:number}>();return NextResponse.json({ok:true,id:(saved?.id??id)||undefined});}
return NextResponse.json({error:'Recurso inválido.'},{status:400});}
export async function DELETE(request:Request){if(!await admin())return NextResponse.json({error:'Acceso requerido.'},{status:403});const body=await request.json() as Record<string,unknown>;const db=await ensureDatabase();if(String(body.resource)==='menu'){await db.prepare('DELETE FROM menu_items WHERE id=?').bind(Number(body.id)).run();return NextResponse.json({ok:true});}if(String(body.resource)==='category'){const table=categoryTables[String(body.entity??'')];if(!table)return NextResponse.json({error:'Categoría inválida.'},{status:400});await db.prepare(`DELETE FROM ${table} WHERE id=?`).bind(Number(body.id)).run();return NextResponse.json({ok:true});}return NextResponse.json({error:'Recurso inválido.'},{status:400});}
