import { NextResponse } from 'next/server';
import { getChatGPTUser,isAdminEmail } from '../../../chatgpt-auth';
import { ensureDatabase,slugify } from '../../../../db/runtime';
const categoryTables:Record<string,string>={tour:'categories',service:'service_categories',lodging:'lodging_categories',post:'post_categories',faq:'faq_categories'};
async function admin(){const user=await getChatGPTUser();return Boolean(user&&isAdminEmail(user.email))}
export async function GET(){if(!await admin())return NextResponse.json({error:'Acceso requerido.'},{status:403});const db=await ensureDatabase();const [pages,menu,tour,service,lodging,post,faq]=await Promise.all([db.prepare('SELECT * FROM site_pages ORDER BY page_key').all(),db.prepare('SELECT * FROM menu_items ORDER BY position,sort_order,id').all(),db.prepare('SELECT * FROM categories ORDER BY name').all(),db.prepare('SELECT * FROM service_categories ORDER BY sort_order,name').all(),db.prepare('SELECT * FROM lodging_categories ORDER BY sort_order,name').all(),db.prepare('SELECT * FROM post_categories ORDER BY sort_order,name').all(),db.prepare('SELECT * FROM faq_categories ORDER BY sort_order,name').all()]);return NextResponse.json({pages:pages.results,menu:menu.results,categories:{tour:tour.results,service:service.results,lodging:lodging.results,post:post.results,faq:faq.results}})}
export async function POST(request:Request){if(!await admin())return NextResponse.json({error:'Acceso requerido.'},{status:403});const body=await request.json() as Record<string,unknown>;const db=await ensureDatabase();const resource=String(body.resource??'');
if(resource==='page'){const key=String(body.pageKey??'home');await db.prepare(`INSERT INTO site_pages (page_key,eyebrow,title,description,image,buttons,meta,updated_at) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(page_key) DO UPDATE SET eyebrow=excluded.eyebrow,title=excluded.title,description=excluded.description,image=excluded.image,buttons=excluded.buttons,meta=excluded.meta,updated_at=excluded.updated_at`).bind(key,String(body.eyebrow??''),String(body.title??''),String(body.description??''),String(body.image??''),String(body.buttons??'[]'),String(body.meta??'[]'),new Date().toISOString()).run();return NextResponse.json({ok:true});}
if(resource==='menu'){const id=Number(body.id||0);if(id)await db.prepare('UPDATE menu_items SET label=?,url=?,position=?,sort_order=?,active=?,open_new_tab=? WHERE id=?').bind(String(body.label??''),String(body.url??'/'),String(body.position??'main'),Number(body.sortOrder||0),body.active===false?0:1,body.openNewTab?1:0,id).run();else await db.prepare('INSERT INTO menu_items (label,url,position,sort_order,active,open_new_tab) VALUES (?,?,?,?,1,?)').bind(String(body.label??''),String(body.url??'/'),String(body.position??'main'),Number(body.sortOrder||0),body.openNewTab?1:0).run();return NextResponse.json({ok:true});}
if(resource==='category'){const entity=String(body.entity??'');const table=categoryTables[entity];if(!table)return NextResponse.json({error:'Categoría inválida.'},{status:400});const name=String(body.name??'');const slug=slugify(String(body.slug||name));const id=Number(body.id||0);if(table==='categories'){if(id)await db.prepare('UPDATE categories SET name=?,slug=?,description=? WHERE id=?').bind(name,slug,String(body.description??''),id).run();else await db.prepare('INSERT INTO categories (name,slug,description,created_at) VALUES (?,?,?,?)').bind(name,slug,String(body.description??''),new Date().toISOString()).run();}else if(table==='faq_categories'){if(id)await db.prepare('UPDATE faq_categories SET name=?,sort_order=? WHERE id=?').bind(name,Number(body.sortOrder||0),id).run();else await db.prepare('INSERT INTO faq_categories (name,sort_order) VALUES (?,?)').bind(name,Number(body.sortOrder||0)).run();}else if(id)await db.prepare(`UPDATE ${table} SET name=?,slug=?,description=?,sort_order=?,active=1 WHERE id=?`).bind(name,slug,String(body.description??''),Number(body.sortOrder||0),id).run();else await db.prepare(`INSERT INTO ${table} (name,slug,description,sort_order,active) VALUES (?,?,?,?,1)`).bind(name,slug,String(body.description??''),Number(body.sortOrder||0)).run();return NextResponse.json({ok:true});}
return NextResponse.json({error:'Recurso inválido.'},{status:400});}
export async function DELETE(request:Request){if(!await admin())return NextResponse.json({error:'Acceso requerido.'},{status:403});const body=await request.json() as Record<string,unknown>;const db=await ensureDatabase();if(String(body.resource)==='menu'){await db.prepare('DELETE FROM menu_items WHERE id=?').bind(Number(body.id)).run();return NextResponse.json({ok:true});}if(String(body.resource)==='category'){const table=categoryTables[String(body.entity??'')];if(!table)return NextResponse.json({error:'Categoría inválida.'},{status:400});await db.prepare(`DELETE FROM ${table} WHERE id=?`).bind(Number(body.id)).run();return NextResponse.json({ok:true});}return NextResponse.json({error:'Recurso inválido.'},{status:400});}
