import { NextResponse } from 'next/server';
import { getChatGPTUser,isAdminEmail } from '../../chatgpt-auth';
import { ensureDatabase, slugify } from '../../../db/runtime';
const allowed=['tours','categories','services','lodgings','posts','faqs','policies','bookings','reviews'];
export async function GET(request:Request){const type=new URL(request.url).searchParams.get('type')??'tours';if(!allowed.includes(type))return NextResponse.json({error:'Tipo inválido'},{status:400});if(['bookings','reviews'].includes(type)){const auth=await adminUser();if(auth.error)return auth.error;}const db=await ensureDatabase();const result=await db.prepare(`SELECT * FROM ${type} ORDER BY id DESC LIMIT 100`).all();return NextResponse.json(result.results);}
async function adminUser(){const user=await getChatGPTUser();if(!user)return{error:NextResponse.json({error:'Inicia sesión para administrar contenido.'},{status:401})};if(!isAdminEmail(user.email))return{error:NextResponse.json({error:'Acceso de administrador requerido.'},{status:403})};return{user};}
export async function POST(request:Request){const auth=await adminUser();if(auth.error)return auth.error;const body=await request.json() as Record<string,unknown>;const type=String(body.type??'');const db=await ensureDatabase();const now=new Date().toISOString();
if(type==='tour'){const name=String(body.name??'');const slug=slugify(String(body.slug||name));await db.prepare(`INSERT INTO tours (slug,name,h1,meta_description,keywords,description,location,meeting_point,departure_time,duration,difficulty,capacity,price_type,person_price,group_price,season_prices,includes,not_included,bring,prohibited,recommendations,extra_messages,gallery,cover_image,policy_id,status,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(slug,name,String(body.h1||name),String(body.metaDescription||''),String(body.keywords||''),String(body.description||''),String(body.location||''),String(body.meetingPoint||''),String(body.departureTime||''),String(body.duration||''),String(body.difficulty||'Fácil'),String(body.capacity||''),String(body.priceType||'person'),Number(body.personPrice||0),Number(body.groupPrice||0),String(body.seasonPrices||''),String(body.includes||''),String(body.notIncluded||''),String(body.bring||''),String(body.prohibited||''),String(body.recommendations||''),String(body.extraMessages||''),String(body.gallery||'[]'),String(body.coverImage||''),body.policyId?Number(body.policyId):null,'published',now).run();return NextResponse.json({ok:true,slug});}
if(type==='category'){const name=String(body.name??'');await db.prepare(`INSERT INTO categories (name,slug,description,created_at) VALUES (?,?,?,?)`).bind(name,slugify(name),String(body.description||''),now).run();}
else if(type==='service'){const name=String(body.name??'');const slug=slugify(String(body.slug||name));await db.prepare(`INSERT INTO services (name,slug,description,price_type,price,image,active,created_at) VALUES (?,?,?,?,?,?,1,?)`).bind(name,slug,String(body.description||''),String(body.priceType||'service'),Number(body.price||0),String(body.image||body.coverImage||''),now).run();return NextResponse.json({ok:true,slug});}
else if(type==='lodging'){const name=String(body.name??'');await db.prepare(`INSERT INTO lodgings (name,slug,location,description,price_type,person_price,group_price,active,created_at) VALUES (?,?,?,?,?,?,?,1,?)`).bind(name,slugify(name),String(body.location||''),String(body.description||''),String(body.priceType||'person'),Number(body.personPrice||0),Number(body.groupPrice||0),now).run();}
else if(type==='post'){const title=String(body.title??'');await db.prepare(`INSERT INTO posts (title,slug,excerpt,content,status,published_at,created_at) VALUES (?,?,?,?, 'published',?,?)`).bind(title,slugify(title),String(body.excerpt||''),String(body.content||''),now,now).run();}
else if(type==='faq'){await db.prepare(`INSERT INTO faqs (question,answer,sort_order,active) VALUES (?,?,0,1)`).bind(String(body.question||''),String(body.answer||'')).run();}
else if(type==='policy'){await db.prepare(`INSERT INTO policies (name,content,is_global,created_at) VALUES (?,?,?,?)`).bind(String(body.name||''),String(body.content||''),body.isGlobal?1:0,now).run();}
else return NextResponse.json({error:'Tipo inválido'},{status:400});return NextResponse.json({ok:true});}

export async function PUT(request:Request){const auth=await adminUser();if(auth.error)return auth.error;const body=await request.json() as Record<string,unknown>;const type=String(body.type??'');const db=await ensureDatabase();const now=new Date().toISOString();
if(type==='service'){const name=String(body.name??'').trim();const slug=slugify(String(body.slug||name));await db.prepare(`INSERT INTO services (name,slug,description,price_type,price,image,active,created_at) VALUES (?,?,?,?,?,?,1,?) ON CONFLICT(slug) DO UPDATE SET name=excluded.name,description=excluded.description,price_type=excluded.price_type,price=excluded.price,image=excluded.image,active=1`).bind(name,slug,String(body.description||''),String(body.priceType||'service'),Number(body.price||0),String(body.image||body.coverImage||''),now).run();return NextResponse.json({ok:true,slug});}
if(type==='tour'){const name=String(body.name??'').trim();const slug=slugify(String(body.slug||name));await db.prepare(`INSERT INTO tours (slug,name,h1,meta_description,keywords,description,location,meeting_point,departure_time,duration,difficulty,capacity,price_type,person_price,group_price,season_prices,includes,not_included,bring,prohibited,recommendations,extra_messages,gallery,cover_image,policy_id,status,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?, 'published',?) ON CONFLICT(slug) DO UPDATE SET name=excluded.name,h1=excluded.h1,meta_description=excluded.meta_description,keywords=excluded.keywords,description=excluded.description,location=excluded.location,meeting_point=excluded.meeting_point,departure_time=excluded.departure_time,duration=excluded.duration,difficulty=excluded.difficulty,capacity=excluded.capacity,price_type=excluded.price_type,person_price=excluded.person_price,group_price=excluded.group_price,season_prices=excluded.season_prices,includes=excluded.includes,not_included=excluded.not_included,bring=excluded.bring,prohibited=excluded.prohibited,recommendations=excluded.recommendations,extra_messages=excluded.extra_messages,gallery=excluded.gallery,cover_image=excluded.cover_image,status='published'`).bind(slug,name,String(body.h1||name),String(body.metaDescription||''),String(body.keywords||''),String(body.description||''),String(body.location||''),String(body.meetingPoint||''),String(body.departureTime||''),String(body.duration||''),String(body.difficulty||'Fácil'),String(body.capacity||''),String(body.priceType||'person'),Number(body.personPrice||0),Number(body.groupPrice||0),String(body.seasonPrices||''),String(body.includes||''),String(body.notIncluded||''),String(body.bring||''),String(body.prohibited||''),String(body.recommendations||''),String(body.extraMessages||''),String(body.gallery||'[]'),String(body.coverImage||''),body.policyId?Number(body.policyId):null,now).run();return NextResponse.json({ok:true,slug});}
if(type==='category'){const name=String(body.name??'');const slug=slugify(String(body.slug||name));await db.prepare(`INSERT INTO categories (name,slug,description,created_at) VALUES (?,?,?,?) ON CONFLICT(slug) DO UPDATE SET name=excluded.name,description=excluded.description`).bind(name,slug,String(body.description||''),now).run();return NextResponse.json({ok:true,slug});}
if(type==='lodging'){const name=String(body.name??'');const slug=slugify(String(body.slug||name));await db.prepare(`INSERT INTO lodgings (name,slug,location,description,price_type,person_price,group_price,image,active,created_at) VALUES (?,?,?,?,?,?,?,?,1,?) ON CONFLICT(slug) DO UPDATE SET name=excluded.name,location=excluded.location,description=excluded.description,price_type=excluded.price_type,person_price=excluded.person_price,group_price=excluded.group_price,image=excluded.image,active=1`).bind(name,slug,String(body.location||''),String(body.description||''),String(body.priceType||'person'),Number(body.personPrice||0),Number(body.groupPrice||0),String(body.image||body.coverImage||''),now).run();return NextResponse.json({ok:true,slug});}
if(type==='post'){const title=String(body.title??'');const slug=slugify(String(body.slug||title));await db.prepare(`INSERT INTO posts (title,slug,excerpt,content,cover_image,status,published_at,created_at) VALUES (?,?,?,?,?,'published',?,?) ON CONFLICT(slug) DO UPDATE SET title=excluded.title,excerpt=excluded.excerpt,content=excluded.content,cover_image=excluded.cover_image,status='published',published_at=excluded.published_at`).bind(title,slug,String(body.excerpt||''),String(body.content||''),String(body.coverImage||''),now,now).run();return NextResponse.json({ok:true,slug});}
if(type==='faq'){const id=Number(body.id||0);if(id)await db.prepare('UPDATE faqs SET question=?,answer=?,active=1 WHERE id=?').bind(String(body.question||''),String(body.answer||''),id).run();else await db.prepare('INSERT INTO faqs (question,answer,sort_order,active) VALUES (?,?,0,1)').bind(String(body.question||''),String(body.answer||'')).run();return NextResponse.json({ok:true});}
if(type==='policy'){const id=Number(body.id||0);if(id)await db.prepare('UPDATE policies SET name=?,content=?,is_global=? WHERE id=?').bind(String(body.name||''),String(body.content||''),body.isGlobal?1:0,id).run();else await db.prepare('INSERT INTO policies (name,content,is_global,created_at) VALUES (?,?,?,?)').bind(String(body.name||''),String(body.content||''),body.isGlobal?1:0,now).run();return NextResponse.json({ok:true});}
return NextResponse.json({error:'Tipo inválido.'},{status:400});}
