import { NextResponse } from 'next/server';
import { getChatGPTUser,isAdminEmail } from '../../chatgpt-auth';
import { ensureDatabase, slugify } from '../../../db/runtime';
import { sanitizeRichHtml } from '../../lib/rich-html';
const allowed=['tours','categories','services','lodgings','posts','faqs','policies','bookings','reviews'];
export async function GET(request:Request){const url=new URL(request.url);const type=url.searchParams.get('type')??'tours';if(!allowed.includes(type))return NextResponse.json({error:'Tipo inválido'},{status:400});if(['bookings','reviews'].includes(type)||url.searchParams.get('includeTombstones')==='1'||url.searchParams.get('status')==='draft'){const auth=await adminUser();if(auth.error)return auth.error;}const db=await ensureDatabase();const draftOnly=url.searchParams.get('status')==='draft';let sql=`SELECT * FROM ${type}`;if(draftOnly&&(type==='tours'||type==='posts'))sql+=" WHERE status='draft'";else if(draftOnly&&['services','lodgings','faqs'].includes(type))sql+=' WHERE active=0';sql+=' ORDER BY id DESC LIMIT 100';const result=await db.prepare(sql).all();if(url.searchParams.get('includeTombstones')==='1'){const tombstones=await db.prepare('SELECT content_key FROM content_tombstones WHERE entity=?').bind(type).all<{content_key:string}>();return NextResponse.json({rows:result.results,tombstones:tombstones.results.map(row=>row.content_key)});}return NextResponse.json(result.results);}
async function adminUser(){const user=await getChatGPTUser();if(!user)return{error:NextResponse.json({error:'Inicia sesión para administrar contenido.'},{status:401})};if(!isAdminEmail(user.email))return{error:NextResponse.json({error:'Acceso de administrador requerido.'},{status:403})};return{user};}
export async function POST(request:Request){const auth=await adminUser();if(auth.error)return auth.error;const body=await request.json() as Record<string,unknown>;const type=String(body.type??'');const db=await ensureDatabase();const now=new Date().toISOString();
if(body.archive===true){const t=String(body.type??'');const slug=String(body.slug??'');if(t==='tours'||t==='posts')await db.prepare(`UPDATE ${t} SET status='draft' WHERE slug=?`).bind(slug).run();else if(['services','lodgings','faqs'].includes(t))await db.prepare(`UPDATE ${t} SET active=0 WHERE slug=?`).bind(slug).run();await db.prepare('INSERT INTO content_tombstones (entity,content_key,created_at) VALUES (?,?,?) ON CONFLICT(entity,content_key) DO NOTHING').bind(t,slug,now).run();return NextResponse.json({ok:true});}
if(body.restore===true){const t=String(body.type??'');const slug=String(body.slug??'');if(t==='tours'||t==='posts')await db.prepare(`UPDATE ${t} SET status='published' WHERE slug=?`).bind(slug).run();else if(['services','lodgings','faqs'].includes(t))await db.prepare(`UPDATE ${t} SET active=1 WHERE slug=?`).bind(slug).run();await db.prepare('DELETE FROM content_tombstones WHERE entity=? AND content_key=?').bind(t,slug).run();return NextResponse.json({ok:true});}
if(body.toggleHome){const slug=String(body.slug??'');const row=await db.prepare('SELECT show_home FROM tours WHERE slug=?').bind(slug).first<{show_home:number}>();const next=row?.show_home?0:1;await db.prepare('UPDATE tours SET show_home=? WHERE slug=?').bind(next,slug).run();return NextResponse.json({ok:true,showHome:next});}
if(type==='tour'){const name=String(body.name??'');const slug=slugify(String(body.slug||name));await db.prepare(`INSERT INTO tours (slug,name,h1,meta_description,keywords,description,location,meeting_point,departure_time,duration,difficulty,capacity,price_type,person_price,group_price,season_prices,includes,not_included,bring,prohibited,recommendations,extra_messages,gallery,cover_image,policy_id,status,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(slug,name,String(body.h1||name),String(body.metaDescription||''),String(body.keywords||''),sanitizeRichHtml(body.description),String(body.location||''),String(body.meetingPoint||''),String(body.departureTime||''),String(body.duration||''),String(body.difficulty||'Fácil'),String(body.capacity||''),String(body.priceType||'person'),Number(body.personPrice||0),Number(body.groupPrice||0),String(body.seasonPrices||''),String(body.includes||''),String(body.notIncluded||''),String(body.bring||''),String(body.prohibited||''),String(body.recommendations||''),String(body.extraMessages||''),String(body.gallery||'[]'),String(body.coverImage||''),body.policyId?Number(body.policyId):null,'published',now).run();if(body.categoryId)await db.prepare('UPDATE tours SET category_id=? WHERE slug=?').bind(Number(body.categoryId),slug).run();return NextResponse.json({ok:true,slug});}
if(type==='category'){const name=String(body.name??'');await db.prepare(`INSERT INTO categories (name,slug,description,created_at) VALUES (?,?,?,?)`).bind(name,slugify(name),String(body.description||''),now).run();}
else if(type==='service'){const name=String(body.name??'');const slug=slugify(String(body.slug||name));await db.prepare(`INSERT INTO services (name,slug,description,price_type,price,image,active,created_at) VALUES (?,?,?,?,?,?,1,?)`).bind(name,slug,String(body.description||''),String(body.priceType||'service'),Number(body.price||0),String(body.image||body.coverImage||''),now).run();if(body.categoryId)await db.prepare('UPDATE services SET category_id=? WHERE slug=?').bind(Number(body.categoryId),slug).run();return NextResponse.json({ok:true,slug});}
else if(type==='lodging'){const name=String(body.name??'');const slug=slugify(String(body.slug||name));await db.prepare(`INSERT INTO lodgings (name,slug,location,description,price_type,person_price,group_price,active,created_at) VALUES (?,?,?,?,?,?,?,1,?)`).bind(name,slug,String(body.location||''),String(body.description||''),String(body.priceType||'person'),Number(body.personPrice||0),Number(body.groupPrice||0),now).run();if(body.categoryId)await db.prepare('UPDATE lodgings SET category_id=? WHERE slug=?').bind(Number(body.categoryId),slug).run();}
else if(type==='post'){const title=String(body.title??'');const slug=slugify(String(body.slug||title));await db.prepare(`INSERT INTO posts (title,slug,excerpt,content,cover_image,status,published_at,created_at) VALUES (?,?,?,?,?,'published',?,?)`).bind(title,slug,String(body.excerpt||''),sanitizeRichHtml(body.content),String(body.coverImage||''),now,now).run();if(body.categoryId)await db.prepare('UPDATE posts SET category_id=? WHERE slug=?').bind(Number(body.categoryId),slug).run();}
else if(type==='faq'){await db.prepare(`INSERT INTO faqs (category_id,question,answer,sort_order,active) VALUES (?,?,?,0,1)`).bind(body.categoryId?Number(body.categoryId):null,String(body.question||''),String(body.answer||'')).run();}
else if(type==='policy'){await db.prepare(`INSERT INTO policies (name,content,is_global,created_at) VALUES (?,?,?,?)`).bind(String(body.name||''),String(body.content||''),body.isGlobal?1:0,now).run();}
else return NextResponse.json({error:'Tipo inválido'},{status:400});return NextResponse.json({ok:true});}

export async function PUT(request:Request){const auth=await adminUser();if(auth.error)return auth.error;const body=await request.json() as Record<string,unknown>;const type=String(body.type??'');const db=await ensureDatabase();const now=new Date().toISOString();
if(type==='service'){const name=String(body.name??'').trim();const slug=slugify(String(body.slug||name));await db.prepare(`INSERT INTO services (name,slug,description,price_type,price,image,active,created_at) VALUES (?,?,?,?,?,?,1,?) ON CONFLICT(slug) DO UPDATE SET name=excluded.name,description=excluded.description,price_type=excluded.price_type,price=excluded.price,image=excluded.image,active=1`).bind(name,slug,String(body.description||''),String(body.priceType||'service'),Number(body.price||0),String(body.image||body.coverImage||''),now).run();await db.prepare('UPDATE services SET category_id=? WHERE slug=?').bind(body.categoryId?Number(body.categoryId):null,slug).run();return NextResponse.json({ok:true,slug});}
if(type==='tour'){const name=String(body.name??'').trim();const slug=slugify(String(body.slug||name));await db.prepare(`INSERT INTO tours (slug,name,h1,meta_description,keywords,description,location,meeting_point,departure_time,duration,difficulty,capacity,price_type,person_price,group_price,season_prices,includes,not_included,bring,prohibited,recommendations,extra_messages,gallery,cover_image,policy_id,status,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?, 'published',?) ON CONFLICT(slug) DO UPDATE SET name=excluded.name,h1=excluded.h1,meta_description=excluded.meta_description,keywords=excluded.keywords,description=excluded.description,location=excluded.location,meeting_point=excluded.meeting_point,departure_time=excluded.departure_time,duration=excluded.duration,difficulty=excluded.difficulty,capacity=excluded.capacity,price_type=excluded.price_type,person_price=excluded.person_price,group_price=excluded.group_price,season_prices=excluded.season_prices,includes=excluded.includes,not_included=excluded.not_included,bring=excluded.bring,prohibited=excluded.prohibited,recommendations=excluded.recommendations,extra_messages=excluded.extra_messages,gallery=excluded.gallery,cover_image=excluded.cover_image,status='published'`).bind(slug,name,String(body.h1||name),String(body.metaDescription||''),String(body.keywords||''),sanitizeRichHtml(body.description),String(body.location||''),String(body.meetingPoint||''),String(body.departureTime||''),String(body.duration||''),String(body.difficulty||'Fácil'),String(body.capacity||''),String(body.priceType||'person'),Number(body.personPrice||0),Number(body.groupPrice||0),String(body.seasonPrices||''),String(body.includes||''),String(body.notIncluded||''),String(body.bring||''),String(body.prohibited||''),String(body.recommendations||''),String(body.extraMessages||''),String(body.gallery||'[]'),String(body.coverImage||''),body.policyId?Number(body.policyId):null,now).run();await db.prepare('UPDATE tours SET category_id=? WHERE slug=?').bind(body.categoryId?Number(body.categoryId):null,slug).run();return NextResponse.json({ok:true,slug});}
if(type==='category'){const name=String(body.name??'');const slug=slugify(String(body.slug||name));await db.prepare(`INSERT INTO categories (name,slug,description,created_at) VALUES (?,?,?,?) ON CONFLICT(slug) DO UPDATE SET name=excluded.name,description=excluded.description`).bind(name,slug,String(body.description||''),now).run();return NextResponse.json({ok:true,slug});}
if(type==='lodging'){const name=String(body.name??'');const slug=slugify(String(body.slug||name));await db.prepare(`INSERT INTO lodgings (name,slug,location,description,price_type,person_price,group_price,image,active,created_at) VALUES (?,?,?,?,?,?,?,?,1,?) ON CONFLICT(slug) DO UPDATE SET name=excluded.name,location=excluded.location,description=excluded.description,price_type=excluded.price_type,person_price=excluded.person_price,group_price=excluded.group_price,image=excluded.image,active=1`).bind(name,slug,String(body.location||''),String(body.description||''),String(body.priceType||'person'),Number(body.personPrice||0),Number(body.groupPrice||0),String(body.image||body.coverImage||''),now).run();await db.prepare('UPDATE lodgings SET category_id=? WHERE slug=?').bind(body.categoryId?Number(body.categoryId):null,slug).run();return NextResponse.json({ok:true,slug});}
if(type==='post'){const title=String(body.title??'');const slug=slugify(String(body.slug||title));await db.prepare(`INSERT INTO posts (title,slug,excerpt,content,cover_image,status,published_at,created_at) VALUES (?,?,?,?,?,'published',?,?) ON CONFLICT(slug) DO UPDATE SET title=excluded.title,excerpt=excluded.excerpt,content=excluded.content,cover_image=excluded.cover_image,status='published',published_at=excluded.published_at`).bind(title,slug,String(body.excerpt||''),sanitizeRichHtml(body.content),String(body.coverImage||''),now,now).run();await db.prepare('UPDATE posts SET category_id=? WHERE slug=?').bind(body.categoryId?Number(body.categoryId):null,slug).run();return NextResponse.json({ok:true,slug});}
if(type==='faq'){const id=Number(body.id||0);if(id)await db.prepare('UPDATE faqs SET category_id=?,question=?,answer=?,active=1 WHERE id=?').bind(body.categoryId?Number(body.categoryId):null,String(body.question||''),String(body.answer||''),id).run();else await db.prepare('INSERT INTO faqs (category_id,question,answer,sort_order,active) VALUES (?,?,?,0,1)').bind(body.categoryId?Number(body.categoryId):null,String(body.question||''),String(body.answer||'')).run();return NextResponse.json({ok:true});}
if(type==='policy'){const id=Number(body.id||0);if(id)await db.prepare('UPDATE policies SET name=?,content=?,is_global=? WHERE id=?').bind(String(body.name||''),String(body.content||''),body.isGlobal?1:0,id).run();else await db.prepare('INSERT INTO policies (name,content,is_global,created_at) VALUES (?,?,?,?)').bind(String(body.name||''),String(body.content||''),body.isGlobal?1:0,now).run();return NextResponse.json({ok:true});}
return NextResponse.json({error:'Tipo inválido.'},{status:400});}

export async function DELETE(request:Request){const auth=await adminUser();if(auth.error)return auth.error;const body=await request.json() as Record<string,unknown>;const kind=String(body.type??'');const map:Record<string,string>={tour:'tours',service:'services',lodging:'lodgings',post:'posts',faq:'faqs',policy:'policies'};const table=map[kind];const id=Number(body.id||0);const key=String(body.key??'').trim();if(!table||!key)return NextResponse.json({error:'Registro inválido.'},{status:400});const db=await ensureDatabase();if(id)await db.prepare(`DELETE FROM ${table} WHERE id=?`).bind(id).run();else if(['tour','service','lodging','post'].includes(kind))await db.prepare(`DELETE FROM ${table} WHERE slug=?`).bind(key).run();await db.prepare('INSERT INTO content_tombstones (entity,content_key,created_at) VALUES (?,?,?) ON CONFLICT(entity,content_key) DO UPDATE SET created_at=excluded.created_at').bind(table,key,new Date().toISOString()).run();return NextResponse.json({ok:true});}
