import { NextResponse } from 'next/server';
import { getChatGPTUser,isAdminEmail } from '../../chatgpt-auth';
import { ensureDatabase, slugify } from '../../../db/runtime';
const allowed=['tours','categories','services','lodgings','posts','faqs','policies','bookings','reviews'];
export async function GET(request:Request){const type=new URL(request.url).searchParams.get('type')??'tours';if(!allowed.includes(type))return NextResponse.json({error:'Tipo inválido'},{status:400});const db=await ensureDatabase();const result=await db.prepare(`SELECT * FROM ${type} ORDER BY id DESC LIMIT 100`).all();return NextResponse.json(result.results);}
async function adminUser(){const user=await getChatGPTUser();if(!user)return{error:NextResponse.json({error:'Inicia sesión para administrar contenido.'},{status:401})};if(!isAdminEmail(user.email))return{error:NextResponse.json({error:'Acceso de administrador requerido.'},{status:403})};return{user};}
export async function POST(request:Request){const auth=await adminUser();if(auth.error)return auth.error;const body=await request.json() as Record<string,unknown>;const type=String(body.type??'');const db=await ensureDatabase();const now=new Date().toISOString();
if(type==='tour'){const name=String(body.name??'');const slug=slugify(String(body.slug||name));await db.prepare(`INSERT INTO tours (slug,name,h1,meta_description,keywords,description,location,duration,difficulty,capacity,price_type,person_price,group_price,season_prices,includes,bring,prohibited,gallery,cover_image,policy_id,status,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(slug,name,String(body.h1||name),String(body.metaDescription||''),String(body.keywords||''),String(body.description||''),String(body.location||''),String(body.duration||''),String(body.difficulty||'Fácil'),String(body.capacity||''),String(body.priceType||'person'),Number(body.personPrice||0),Number(body.groupPrice||0),String(body.seasonPrices||''),String(body.includes||''),String(body.bring||''),String(body.prohibited||''),String(body.gallery||'[]'),String(body.coverImage||''),body.policyId?Number(body.policyId):null,'published',now).run();return NextResponse.json({ok:true,slug});}
if(type==='category'){const name=String(body.name??'');await db.prepare(`INSERT INTO categories (name,slug,description,created_at) VALUES (?,?,?,?)`).bind(name,slugify(name),String(body.description||''),now).run();}
else if(type==='service'){const name=String(body.name??'');const slug=slugify(String(body.slug||name));await db.prepare(`INSERT INTO services (name,slug,description,price_type,price,image,active,created_at) VALUES (?,?,?,?,?,?,1,?)`).bind(name,slug,String(body.description||''),String(body.priceType||'service'),Number(body.price||0),String(body.image||body.coverImage||''),now).run();return NextResponse.json({ok:true,slug});}
else if(type==='lodging'){const name=String(body.name??'');await db.prepare(`INSERT INTO lodgings (name,slug,location,description,price_type,person_price,group_price,active,created_at) VALUES (?,?,?,?,?,?,?,1,?)`).bind(name,slugify(name),String(body.location||''),String(body.description||''),String(body.priceType||'person'),Number(body.personPrice||0),Number(body.groupPrice||0),now).run();}
else if(type==='post'){const title=String(body.title??'');await db.prepare(`INSERT INTO posts (title,slug,excerpt,content,status,published_at,created_at) VALUES (?,?,?,?, 'published',?,?)`).bind(title,slugify(title),String(body.excerpt||''),String(body.content||''),now,now).run();}
else if(type==='faq'){await db.prepare(`INSERT INTO faqs (question,answer,sort_order,active) VALUES (?,?,0,1)`).bind(String(body.question||''),String(body.answer||'')).run();}
else if(type==='policy'){await db.prepare(`INSERT INTO policies (name,content,is_global,created_at) VALUES (?,?,?,?)`).bind(String(body.name||''),String(body.content||''),body.isGlobal?1:0,now).run();}
else return NextResponse.json({error:'Tipo inválido'},{status:400});return NextResponse.json({ok:true});}

export async function PUT(request:Request){const auth=await adminUser();if(auth.error)return auth.error;const body=await request.json() as Record<string,unknown>;if(String(body.type)!=='service')return NextResponse.json({error:'Solo la edición de servicios está disponible.'},{status:400});const name=String(body.name??'').trim();const slug=slugify(String(body.slug||name));if(!name||!slug)return NextResponse.json({error:'Nombre y URL son requeridos.'},{status:400});const db=await ensureDatabase();const now=new Date().toISOString();await db.prepare(`INSERT INTO services (name,slug,description,price_type,price,image,active,created_at) VALUES (?,?,?,?,?,?,1,?) ON CONFLICT(slug) DO UPDATE SET name=excluded.name,description=excluded.description,price_type=excluded.price_type,price=excluded.price,image=excluded.image,active=1`).bind(name,slug,String(body.description||''),String(body.priceType||'service'),Number(body.price||0),String(body.image||body.coverImage||''),now).run();return NextResponse.json({ok:true,slug});}
