export type PriceType = 'person' | 'group';
export type Tour = {
  slug:string; name:string; h1:string; category:string; location:string;
  price:number; priceType:PriceType; groupPrice?:number; seasonPrices?:string;
  policy?:string; duration:string; difficulty:string; difficultyScore:number;
  capacity:string; minPeople:number; image:string; short:string;
  meetingPoint?:string; departureTime?:string; includes?:string[];
  notIncluded?:string[]; bring?:string[]; prohibited?:string[];
  recommendations?:string[]; extraMessages?:string[];
};

export const tours: Tour[] = [
  { slug:'kayak-chiriqui', name:'Tour en Kayak en Chiriquí', h1:'Tour en Kayak en Chiriquí, Panamá | Inolvidable', category:'Agua e islas', location:'Golfo de Chiriquí', price:95, priceType:'person', duration:'8 horas', departureTime:'7:00 a. m.', difficulty:'Moderada', difficultyScore:6, capacity:'2–10 personas', minPeople:2, image:'https://images.unsplash.com/photo-1526772662000-3f88f10405ff?auto=format&fit=crop&w=1200&q=85', short:'Rema entre islas tropicales, manglares y aguas cristalinas del Pacífico.', includes:['Kayak y remo','Chaleco salvavidas','Guía local','Agua y snack'],notIncluded:['Compras personales','Transporte fuera de la ruta acordada'],bring:['Ropa de secado rápido','Protector solar','Cambio de ropa','Bolsa impermeable'],recommendations:['Llega 15 minutos antes del horario acordado.','Protege teléfonos y objetos personales del agua.'] },
  { slug:'volcan-baru-4x4', name:'Vibrante Volcán Barú 4×4', h1:'Subir Volcán Barú en 4×4 | Vibrante Volcán Barú 4×4', category:'Montaña', location:'Boquete, Chiriquí', price:520, priceType:'group', groupPrice:520, seasonPrices:'[{"name":"Temporada alta","start":"2026-12-15","end":"2027-04-15","groupPrice":590}]', duration:'6 horas', difficulty:'Media', difficultyScore:5, capacity:'1–8 personas', minPeople:1, image:'https://images.unsplash.com/photo-1551632811-561732d1e306?auto=format&fit=crop&w=1200&q=85', short:'Alcanza el punto más alto de Panamá y contempla dos océanos al amanecer.' },
  { slug:'cafe-boquete', name:'Tour de Café en Boquete', h1:'Tour de Café en Boquete con degustación / increíble', category:'Cultura y café', location:'Boquete, Chiriquí', price:48, priceType:'person', duration:'3 horas', difficulty:'Fácil', difficultyScore:2, capacity:'1–12 personas', minPeople:1, image:'https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=1200&q=85', short:'Conoce el viaje del grano a la taza y degusta cafés de altura excepcionales.' },
  { slug:'islas-boca-chica', name:'Islas de Boca Chica', h1:'Tour de islas en Boca Chica, Chiriquí | Experiencia Inolvidable', category:'Agua e islas', location:'Boca Chica, Chiriquí', price:560, priceType:'group', groupPrice:560, duration:'Día completo', difficulty:'Fácil', difficultyScore:3, capacity:'2–12 personas', minPeople:2, image:'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?auto=format&fit=crop&w=1200&q=85', short:'Navega entre islas vírgenes, haz snorkel y relájate frente al Pacífico.' },
  { slug:'tour-en-bicicleta-montanera-en-chiriqui-panama', name:'Tour en Bicicleta Montañera en David', h1:'Tour en Bicicleta Montañera en David, Chiriquí, Panamá', category:'Bike tours', location:'David, Chiriquí', meetingPoint:'David, Chiriquí', price:55, priceType:'person', duration:'4 horas', difficulty:'Retadora', difficultyScore:6, capacity:'2–10 personas', minPeople:2, image:'https://images.unsplash.com/photo-1541625602330-2277a4c46182?auto=format&fit=crop&w=1200&q=85', short:'Recorre caminos rurales y senderos de montaña en los alrededores de David.', includes:['Bicicleta MTB','Casco y equipo de seguridad','Guía local','Hidratación'] },
  { slug:'tour-en-bicicletas-en-ciudad-de-panama-panama-bike-tour', name:'Panama Bike Tour', h1:'Tour en Bicicletas en Panamá – Panama Bike Tour', category:'Bike tours', location:'David, Chiriquí', meetingPoint:'David, Chiriquí', price:45, priceType:'person', duration:'4 horas', difficulty:'Moderada', difficultyScore:5, capacity:'2–10 personas', minPeople:2, image:'https://images.unsplash.com/photo-1528629297340-d1d466945dc5?auto=format&fit=crop&w=1200&q=85', short:'Una ruta activa con transporte ida y vuelta y acompañamiento local.', includes:['Transporte ida y vuelta','Bicicleta MTB','Casco','Guía local'] },
  { slug:'e-bike-tour-boquete-adventure-san-ramon-waterfall', name:'Tour de Bicicletas en Boquete', h1:'Tour de Bicicletas en Boquete | Increíble', category:'Bike tours', location:'Boquete', meetingPoint:'Boquete, Chiriquí', price:45, priceType:'person', duration:'4 horas', difficulty:'Moderada', difficultyScore:5, capacity:'2–8 personas', minPeople:2, image:'https://images.unsplash.com/photo-1502744688674-c619d1586c9e?auto=format&fit=crop&w=1200&q=85', short:'Pedalea entre montañas y visita la cascada de San Ramón con bicicletas Trek.', includes:['Bicicletas MTB marca Trek','Casco','Guía local','Hidratación'] },
  { slug:'aventura-costera-pedasi', name:'Aventura Costera en Pedasí', h1:'Tour costero en Pedasí, Panamá | Naturaleza y Pacífico', category:'Agua e islas', location:'Pedasí, Los Santos', meetingPoint:'Centro de Pedasí, Los Santos', price:85, priceType:'person', duration:'6 horas', difficulty:'Fácil', difficultyScore:3, capacity:'2–10 personas', minPeople:2, image:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=85', short:'Descubre playas, miradores y la esencia del Pacífico panameño con un guía local.', includes:['Guía local','Transporte desde el punto de encuentro','Agua y snack','Equipo básico'] },
];

export const categories = [
  { name:'Montaña', slug:'montana', icon:'△', count:tours.filter(t=>t.category==='Montaña').length, image:tours[1].image },
  { name:'Agua e islas', slug:'agua-e-islas', icon:'≈', count:tours.filter(t=>t.category==='Agua e islas').length, image:tours[3].image },
  { name:'Cultura y café', slug:'cultura-y-cafe', icon:'✦', count:tours.filter(t=>t.category==='Cultura y café').length, image:tours[2].image },
  { name:'Bike tours', slug:'bike', icon:'◉', count:tours.filter(t=>t.category==='Bike tours').length, image:tours[4].image },
];
