'use client';
import { FormEvent, useState } from 'react';
import { SiteLink as Link } from './site-link';
import { LogoutLink } from './logout-link';
type Props={user:{displayName:string;email:string;fullName:string};profile:Record<string,unknown>;bookings:Array<Record<string,unknown>>;signOutPath:string};
const labels:Record<string,string>={pending:'Pendiente',confirmed:'Confirmado',completed:'Completado',cancelled:'Cancelado',cancellation_requested:'Cancelación solicitada'};
const payLabels:Record<string,string>={cash:'Efectivo',paguelo:'Tarjeta (Paguelo Fácil)',paypal:'PayPal'};
export function AccountDashboard({user,profile,bookings:initialBookings,signOutPath}:Props){
  const [tab,setTab]=useState<'orders'|'profile'|'settings'|'payments'>('orders');
  const [message,setMessage]=useState('');
  const [bookings,setBookings]=useState(initialBookings);
  const [cancelTarget,setCancelTarget]=useState<string|null>(null);
  const [cancelReason,setCancelReason]=useState('');
  const [cancelError,setCancelError]=useState('');
  const [expanded,setExpanded]=useState<string|null>(null);
  async function saveProfile(event:FormEvent<HTMLFormElement>){event.preventDefault();setMessage('Guardando…');const data=Object.fromEntries(new FormData(event.currentTarget).entries()) as Record<string,unknown>;data.marketingOptIn=data.marketingOptIn==='on';const response=await fetch('/api/profile',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(data)});setMessage(response.ok?'Perfil actualizado correctamente.':'No se pudo actualizar el perfil.');}
  function openCancel(reference:string){setCancelTarget(reference);setCancelReason('');setCancelError('');}
  async function submitCancel(){if(!cancelTarget)return;if(!cancelReason.trim()){setCancelError('Escribe el motivo de la cancelación.');return;}const response=await fetch('/api/bookings',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({action:'request_cancel',reference:cancelTarget,reason:cancelReason.trim()})});const data=await response.json() as {error?:string};if(response.ok){setBookings(old=>old.map(row=>String(row.reference)===cancelTarget?{...row,status:'cancellation_requested'}:row));setCancelTarget(null);setCancelReason('');setMessage('Solicitud enviada. Te contactaremos para confirmarla.');}else setCancelError(data.error||'No se pudo enviar la solicitud.');}
  return <section className="account-shell shell"><aside className="account-nav"><div className="user-avatar">{user.displayName.slice(0,2).toUpperCase()}</div><h1>Hola, {user.fullName.split(' ')[0]}</h1><p>{user.email}</p><nav><button className={tab==='orders'?'active':''} onClick={()=>setTab('orders')}>▤ Mis pedidos</button><button className={tab==='profile'?'active':''} onClick={()=>setTab('profile')}>◎ Editar perfil</button><button className={tab==='payments'?'active':''} onClick={()=>setTab('payments')}>◇ Métodos de pago</button><button className={tab==='settings'?'active':''} onClick={()=>setTab('settings')}>⚙ Ajustes</button><LogoutLink href={signOutPath}/></nav></aside><div className="account-content">
  {tab==='orders'&&<><div className="section-heading"><div><p className="eyebrow"><span/> Tu historial</p><h2>Mis pedidos</h2></div><Link className="button button--primary" href="/tours">Nueva reserva</Link></div>{bookings.length===0?<div className="empty-state"><span>△</span><h3>Aún no tienes pedidos</h3><p>Tu próxima historia puede empezar en el Volcán Barú, Boquete o una isla del Pacífico.</p><Link className="button" href="/tours">Ver experiencias</Link></div>:<><div className="booking-list">{bookings.map(row=>{const ref=String(row.reference);const open=expanded===ref;return <article key={ref} className={open?'is-open':''}><div><small>{ref}</small><h3>{String(row.tour_slug).replaceAll('-',' ')}</h3></div><div><small>Fecha</small><b>{String(row.tour_date)}</b></div><div><small>Cantidad</small><b>{String(row.quantity)}</b></div><div><small>Total</small><b>${Number(row.total).toFixed(2)}</b></div><span className={`status-pill status-${String(row.status)}`}>{labels[String(row.status)]??String(row.status)}</span><div className="booking-actions"><button className="order-view" onClick={()=>setExpanded(open?null:ref)}>{open?'Cerrar':'Ver detalle'}</button>{['pending','confirmed'].includes(String(row.status))&&<button className="order-cancel" onClick={()=>openCancel(ref)}>Solicitar cancelación</button>}</div>{open&&<div className="booking-detail"><div><small>Método de pago</small><b>{payLabels[String(row.payment_method)]??String(row.payment_method??'cash')}</b></div><div><small>Estado</small><b>{labels[String(row.status)]??String(row.status)}</b></div><div><small>Creado el</small><b>{row.created_at?new Date(String(row.created_at)).toLocaleString('es-PA',{dateStyle:'medium',timeStyle:'short'}):'—'}</b></div></div>}</article>;})}</div><p className="account-message">{message}</p></>}</>}
  {tab==='profile'&&<section className="account-panel"><p className="eyebrow"><span/> Información personal</p><h2>Editar perfil</h2><form className="admin-form" onSubmit={saveProfile}><div className="form-row"><label>Nombre completo<input name="fullName" required defaultValue={String(profile.full_name??user.fullName)} /></label><label>Correo electrónico<input value={user.email} disabled /></label></div><div className="form-row"><label>Teléfono<input name="phone" defaultValue={String(profile.phone??'')} /></label><label>Ciudad<input name="city" defaultValue={String(profile.city??'')} /></label></div><div className="form-row"><label>País<input name="country" defaultValue={String(profile.country??'Panamá')} /></label><label>Contacto de emergencia<input name="emergencyContact" defaultValue={String(profile.emergency_contact??'')} /></label></div><div className="admin-form__actions"><span>{message}</span><button className="button button--primary">Guardar cambios</button></div></form></section>}
  {tab==='payments'&&<section className="account-panel"><p className="eyebrow"><span/> Pagos seguros</p><h2>Métodos de pago</h2><article className="payment-method"><span>＄</span><div><h3>Efectivo</h3><p>Método activo para las reservas actuales. El equipo confirma los detalles contigo.</p></div><b>Predeterminado</b></article><article className="payment-method"><span>◇</span><div><h3>Tarjeta de Crédito / Débito</h3><p>Paga al momento con Paguelo Fácil al confirmar tu reserva.</p></div><b>Paguelo Fácil</b></article></section>}
  {tab==='settings'&&<section className="account-panel"><p className="eyebrow"><span/> Preferencias</p><h2>Ajustes</h2><form className="admin-form" onSubmit={saveProfile}><input type="hidden" name="fullName" value={String(profile.full_name??user.fullName)}/><input type="hidden" name="phone" value={String(profile.phone??'')}/><input type="hidden" name="country" value={String(profile.country??'Panamá')}/><input type="hidden" name="city" value={String(profile.city??'')}/><input type="hidden" name="emergencyContact" value={String(profile.emergency_contact??'')}/><label className="setting-row"><span><b>Novedades y ofertas</b><small>Recibe novedades de tours y temporadas por correo.</small></span><input type="checkbox" name="marketingOptIn" defaultChecked={Boolean(profile.marketing_opt_in)}/></label><div className="admin-form__actions"><span>{message}</span><button className="button button--primary">Guardar ajustes</button></div></form></section>}</div>
  {cancelTarget&&<div className="modal-overlay" onClick={()=>setCancelTarget(null)}><div className="modal-card" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setCancelTarget(null)} aria-label="Cerrar">×</button><h3>Solicitar cancelación</h3><p>Cuéntanos el motivo para procesar tu solicitud.</p><label>Motivo<textarea value={cancelReason} onChange={e=>setCancelReason(e.target.value)} rows={4} placeholder="Escribe aquí el motivo…"/></label>{cancelError&&<p className="form-status">{cancelError}</p>}<div className="modal-actions"><button className="button" onClick={()=>setCancelTarget(null)}>Volver</button><button className="button button--danger" onClick={submitCancel}>Enviar solicitud</button></div></div></div>}
  </section>;
}
