'use client';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { tours,categories } from '../data';
import { defaultServices } from '../services-data';
import { defaultStays } from '../lodgings-data';

type Row=Record<string,unknown>;
type Booking=Row&{reference:string;tour_slug:string;tour_date:string;customer_name:string;email:string;quantity:number;total:number;status:string};
const nav=[['overview','Resumen','⌂'],['orders','Pedidos','▤'],['calendar','Calendario','□'],['appearance','Portadas','▣'],['menu','Menú','☰'],['categories_custom','Categorías','▦'],['tour','Tours','⌁'],['service','Servicios','✦'],['lodging','Hospedajes','⌂'],['post','Blog','¶'],['faq','FAQs','?'],['policy','Políticas','§'],['profile','Mi perfil','◎']];
const posts=[{slug:'que-llevar-volcan-baru',title:'Qué llevar para subir el Volcán Barú',excerpt:'Una lista práctica para disfrutar el amanecer en la cima.',content:'Guía de preparación para el Volcán Barú.'},{slug:'islas-boca-chica',title:'Boca Chica: islas que tienes que conocer',excerpt:'Playas tranquilas, snorkel y naturaleza.',content:'Guía local de Boca Chica.'},{slug:'cafe-geisha',title:'Por qué el café Geisha es tan especial',excerpt:'Altura y microclimas detrás de una taza excepcional.',content:'Historia del café Geisha panameño.'}];
const faqs=[{question:'¿Cómo reservo un tour?',answer:'Selecciona la fecha y cantidad, agrégalo al carrito y completa tus datos.'},{question:'¿Cómo se paga?',answer:'Por ahora coordinamos el pago en efectivo después de recibir el pedido.'},{question:'¿Qué pasa si llueve?',answer:'La seguridad es prioridad; podemos reprogramar o proponer una alternativa.'}];
const policies=[{name:'Política general de cancelación',content:'Puedes solicitar una reprogramación sin cargo avisando con al menos 72 horas.',is_global:1}];
const demo:Record<string,Row[]>={tour:tours as unknown as Row[],service:defaultServices.map(x=>({...x,price_type:x.priceType})),lodging:defaultStays.map(x=>({...x,price_type:x.priceType,person_price:x.personPrice,group_price:x.groupPrice})),post:posts,faq:faqs,policy:policies};
const dbType:Record<string,string>={tour:'tours',service:'services',lodging:'lodgings',post:'posts',faq:'faqs',policy:'policies'};
const rowKey=(tab:string,row:Row)=>String(row.slug??row.question??row.name??row.id);
const label=(tab:string,row:Row)=>String(row.name??row.title??row.question??row.reference??tab);
const val=(row:Row|null,...keys:string[])=>{for(const key of keys)if(row?.[key]!=null)return String(row[key]);return ''};

export function AdminDashboard(){const [tab,setTab]=useState('overview');const [rows,setRows]=useState<Row[]>([]);const [orders,setOrders]=useState<Booking[]>([]);const [editor,setEditor]=useState<Row|null|undefined>(undefined);const [message,setMessage]=useState('');const [profile,setProfile]=useState<Row>({});const [cms,setCms]=useState<{pages:Row[];menu:Row[];categories:Record<string,Row[]>}>({pages:[],menu:[],categories:{}});
async function loadContent(kind=tab){if(!dbType[kind])return;const res=await fetch(`/api/content?type=${dbType[kind]}`,{cache:'no-store'});const stored=res.ok?await res.json() as Row[]:[];const map=new Map(stored.map(row=>[rowKey(kind,row),row]));const merged=(demo[kind]??[]).map(row=>map.get(rowKey(kind,row))??row);setRows([...merged,...stored.filter(row=>!merged.some(item=>rowKey(kind,item)===rowKey(kind,row)))]);}
async function loadOrders(){const res=await fetch('/api/bookings',{cache:'no-store'});if(res.ok)setOrders(await res.json() as Booking[]);}
async function loadCms(){const res=await fetch('/api/admin/cms',{cache:'no-store'});if(res.ok)setCms(await res.json());}
useEffect(()=>{setEditor(undefined);setMessage('');if(dbType[tab]){void loadContent(tab);void loadCms();}if(['overview','orders','calendar'].includes(tab))void loadOrders();if(['appearance','menu','categories_custom'].includes(tab))void loadCms();if(tab==='profile')fetch('/api/profile').then(r=>r.json()).then(setProfile);},[tab]);
async function upload(file:File){const data=new FormData();data.append('file',file);const res=await fetch('/api/uploads',{method:'POST',body:data});const json=await res.json() as {url?:string;error?:string};if(!res.ok)throw new Error(json.error||'Falló la carga');return json.url!;}
async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();setMessage('Guardando…');const form=event.currentTarget;const data=new FormData(form);const body={...Object.fromEntries(data.entries()),type:tab} as Row;const cover=data.get('coverFile');if(cover instanceof File&&cover.size)body.coverImage=await upload(cover);const gallery=data.getAll('galleryFiles').filter((x):x is File=>x instanceof File&&x.size>0);if(gallery.length)body.gallery=JSON.stringify(await Promise.all(gallery.map(upload)));if(tab==='service')body.image=body.coverImage||body.image;if(editor&&editor.id)body.id=editor.id;const res=await fetch('/api/content',{method:editor?'PUT':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const json=await res.json() as {error?:string};setMessage(res.ok?'Cambios guardados y publicados.':json.error??'No se pudo guardar.');if(res.ok){setEditor(undefined);await loadContent(tab);}}
async function updateOrder(reference:string,status:string){const res=await fetch('/api/bookings',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({reference,status})});if(res.ok){setOrders(old=>old.map(order=>order.reference===reference?{...order,status}:order));setMessage(`Pedido ${reference} actualizado.`);}}
async function removeContent(row:Row){if(!row.id||!confirm(`¿Eliminar ${label(tab,row)}? Esta acción no se puede deshacer.`))return;const res=await fetch('/api/content',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({type:tab,id:row.id})});if(res.ok){setMessage('Registro eliminado.');await loadContent(tab);}else setMessage('No se pudo eliminar el registro.');}
const upcoming=orders.filter(o=>o.status!=='cancelled'&&o.status!=='completed');const total=orders.reduce((sum,o)=>sum+Number(o.total||0),0);const calendar=useMemo(()=>{const grouped=new Map<string,Booking[]>();orders.forEach(order=>grouped.set(order.tour_date,[...(grouped.get(order.tour_date)??[]),order]));return [...grouped.entries()].sort(([a],[b])=>a.localeCompare(b));},[orders]);
return <div className="admin-layout"><aside className="admin-sidebar"><div><span className="admin-dot"/>BONGO <small>ADMIN</small></div><nav>{nav.map(([id,name,icon])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><span>{icon}</span>{name}</button>)}</nav><a href="/">← Ver sitio</a></aside><main className="admin-main"><header><div><p>Gestión operativa</p><h1>{nav.find(x=>x[0]===tab)?.[1]}</h1></div><div className="admin-avatar">BO</div></header>
{tab==='overview'&&<><section className="admin-stats"><article><span>Pedidos</span><strong>{orders.length}</strong><small>Histórico total</small></article><article><span>Próximos</span><strong>{upcoming.length}</strong><small>Por atender</small></article><article><span>Ventas registradas</span><strong>${total.toFixed(2)}</strong><small>Pago coordinado en efectivo</small></article></section><section className="admin-list"><div className="admin-list__head"><div><h2>Próximos pedidos</h2><p>Reservas que requieren seguimiento.</p></div><button className="button button--small" onClick={()=>setTab('orders')}>Ver todos</button></div><OrderRows rows={upcoming.slice(0,6)} onUpdate={updateOrder}/></section></>}
{tab==='orders'&&<section className="admin-list"><div className="admin-list__head"><div><h2>Pedidos y reservas</h2><p>Confirma, completa o cancela pedidos desde un solo lugar.</p></div><span className="status-pill">{orders.length} pedidos</span></div><OrderRows rows={orders} onUpdate={updateOrder}/><p role="status" className="admin-message">{message}</p></section>}
{tab==='calendar'&&<section className="admin-list"><div className="admin-list__head"><div><h2>Calendario de salidas</h2><p>Agenda ordenada por fecha del tour.</p></div><span className="status-pill">{calendar.length} fechas</span></div><div className="admin-calendar">{calendar.length?calendar.map(([date,items])=><article key={date}><time dateTime={date}><b>{new Date(`${date}T12:00:00`).toLocaleDateString('es-PA',{day:'2-digit'})}</b><span>{new Date(`${date}T12:00:00`).toLocaleDateString('es-PA',{month:'short',year:'numeric'})}</span></time><div>{items.map(item=><p key={item.reference}><strong>{item.tour_slug.replaceAll('-',' ')}</strong><span>{item.customer_name} · {item.quantity} · {item.reference}</span></p>)}</div></article>):<Empty text="Todavía no hay reservas en el calendario."/>}</div></section>}
{tab==='appearance'&&<AppearanceManager rows={cms.pages} upload={upload} reload={loadCms}/>}
{tab==='menu'&&<MenuManager rows={cms.menu} reload={loadCms}/>}
{tab==='categories_custom'&&<CategoryManager groups={cms.categories} reload={loadCms}/>}
{dbType[tab]&&<>{editor===undefined?<section className="admin-list"><div className="admin-list__head"><div><h2>Contenido publicado</h2><p>Incluye el contenido demo visible en el sitio y los registros creados en el panel.</p></div><button className="button button--primary button--small" onClick={()=>setEditor(null)}>+ Agregar nuevo</button></div><div className="admin-content-rows">{rows.map(row=><article key={rowKey(tab,row)}><div><b>{label(tab,row)}</b><small>{row.slug?`/${tab==='post'?'blog':tab==='lodging'?'hospedajes':tab==='service'?'servicios':'tours'}/${row.slug}`:'Contenido general'}</small></div><div className="admin-row-actions"><button onClick={()=>setEditor(row)}>Editar</button>{row.id&&<button className="danger" onClick={()=>removeContent(row)}>Eliminar</button>}</div></article>)}</div><p className="admin-message">{message}</p></section>:<Editor tab={tab} row={editor??null} categories={cms.categories[tab]??[]} onSubmit={save} onCancel={()=>setEditor(undefined)} message={message}/>}</>}
{tab==='profile'&&<ProfileEditor profile={profile} onSaved={setMessage} message={message}/>}</main></div>}

function OrderRows({rows,onUpdate}:{rows:Booking[];onUpdate:(reference:string,status:string)=>void}){return <div className="admin-order-table">{rows.length?rows.map(row=><article key={row.reference}><div><small>{row.reference}</small><b>{row.tour_slug.replaceAll('-',' ')}</b><span>{row.customer_name} · {row.email}</span></div><time>{row.tour_date}</time><strong>${Number(row.total).toFixed(2)}</strong><select value={row.status} onChange={e=>onUpdate(row.reference,e.target.value)}><option value="pending">Pendiente</option><option value="cancellation_requested">Cancelación solicitada</option><option value="confirmed">Confirmado</option><option value="completed">Completado</option><option value="cancelled">Cancelado</option></select></article>):<Empty text="Aún no hay pedidos."/>}</div>}
function Empty({text}:{text:string}){return <div className="admin-empty"><span>◇</span><p>{text}</p></div>}
function input(name:string,label:string,row:Row|null,...keys:string[]){return <label>{label}<input name={name} defaultValue={val(row,...keys,name)} /></label>}
function Editor({tab,row,categories,onSubmit,onCancel,message}:{tab:string;row:Row|null;categories:Row[];onSubmit:(e:FormEvent<HTMLFormElement>)=>void;onCancel:()=>void;message:string}){const categorySelect=<label>Categoría<select name="categoryId" defaultValue={val(row,'category_id')}><option value="">Sin categoría</option>{categories.map(c=><option key={String(c.id)} value={String(c.id)}>{String(c.name)}</option>)}</select></label>;return <section className="admin-card"><div className="admin-card__head"><div><button className="admin-back" onClick={onCancel}>← Volver al listado</button><h2>{row?'Editar':'Crear'} contenido</h2><p>El formulario se abre solo al crear o editar.</p></div></div><form className="admin-form" onSubmit={onSubmit}>
{tab==='tour'&&<><div className="form-row">{input('name','Nombre',row)}{input('slug','URL amigable',row)}</div>{categorySelect}{input('h1','H1 para SEO',row)}{input('metaDescription','Meta descripción',row,'meta_description')}{input('keywords','Palabras clave',row)}<label>Descripción<textarea name="description" rows={4} defaultValue={val(row,'description','short')}/></label><div className="form-row">{input('location','Lugar',row)}{input('meetingPoint','Punto de encuentro',row,'meeting_point')}</div><div className="form-row">{input('departureTime','Hora de salida',row,'departure_time')}{input('duration','Duración',row)}</div><div className="form-row">{input('difficulty','Dificultad',row)}{input('capacity','Capacidad',row)}</div><label>Modalidad<select name="priceType" defaultValue={val(row,'price_type','priceType')||'person'}><option value="person">Por persona</option><option value="group">Por grupo</option><option value="both">Ambos</option></select></label><div className="form-row">{input('personPrice','Precio/persona',row,'person_price','price')}{input('groupPrice','Precio/grupo',row,'group_price')}</div>{input('seasonPrices','Precios por temporada (JSON)',row,'season_prices')}<div className="form-row">{input('coverImage','URL de portada',row,'cover_image','image')}<label>Subir portada<input name="coverFile" type="file" accept="image/*"/></label></div><label>Galería<input name="galleryFiles" type="file" accept="image/*" multiple/></label>{['includes','notIncluded','bring','recommendations','prohibited','extraMessages'].map(name=><label key={name}>{({includes:'Qué incluye',notIncluded:'Qué no incluye',bring:'Qué llevar',recommendations:'Recomendaciones',prohibited:'No permitido',extraMessages:'Mensajes extra'} as Record<string,string>)[name]}<textarea name={name} rows={4} defaultValue={Array.isArray(row?.[name])?(row?.[name] as string[]).join('\n'):val(row,name,name.replace(/[A-Z]/g,m=>'_'+m.toLowerCase()))}/></label>)}</>}
{tab==='category'&&<>{input('name','Nombre de categoría',row)}<label>Descripción<textarea name="description" rows={4} defaultValue={val(row,'description')}/></label></>}
{tab==='service'&&<><div className="form-row">{input('name','Nombre',row)}{input('slug','URL amigable',row)}</div>{categorySelect}<label>Descripción<textarea name="description" rows={5} defaultValue={val(row,'description')}/></label><div className="form-row">{input('price','Precio',row)}<label>Modalidad<select name="priceType" defaultValue={val(row,'price_type','priceType')||'service'}><option value="service">Por servicio</option><option value="person">Por persona</option><option value="group">Por grupo</option></select></label></div>{input('image','URL de imagen',row,'image')}<label>Subir imagen<input name="coverFile" type="file" accept="image/*"/></label></>}
{tab==='lodging'&&<>{input('name','Nombre',row)}{input('slug','URL amigable',row)}{categorySelect}{input('location','Ubicación',row)}<label>Descripción<textarea name="description" rows={4} defaultValue={val(row,'description')}/></label><label>Modalidad<select name="priceType" defaultValue={val(row,'price_type','priceType')||'person'}><option value="person">Por persona</option><option value="group">Por grupo</option><option value="both">Ambos</option></select></label><div className="form-row">{input('personPrice','Precio/persona',row,'person_price')}{input('groupPrice','Precio/grupo',row,'group_price')}</div></>}
{tab==='post'&&<>{input('title','Título',row)}{input('slug','URL amigable',row)}{categorySelect}<label>Extracto<textarea name="excerpt" rows={3} defaultValue={val(row,'excerpt')}/></label><label>Contenido<textarea name="content" rows={10} defaultValue={val(row,'content')}/></label></>}
{tab==='faq'&&<>{categorySelect}{input('question','Pregunta',row)}<label>Respuesta<textarea name="answer" rows={5} defaultValue={val(row,'answer')}/></label></>}
{tab==='policy'&&<>{input('name','Nombre',row)}<label>Contenido<textarea name="content" rows={8} defaultValue={val(row,'content')}/></label><label className="check"><input type="checkbox" name="isGlobal" defaultChecked={Boolean(row?.is_global)}/> Usar como política general</label></>}
<div className="admin-form__actions"><span>{message}</span><div><button type="button" className="button" onClick={onCancel}>Cancelar</button><button className="button button--primary">Guardar y publicar</button></div></div></form></section>}
function ProfileEditor({profile,onSaved,message}:{profile:Row;onSaved:(m:string)=>void;message:string}){async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();onSaved('Guardando…');const body=Object.fromEntries(new FormData(e.currentTarget).entries());const res=await fetch('/api/profile',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(body)});onSaved(res.ok?'Perfil actualizado correctamente.':'No se pudo guardar.');}return <section className="admin-card"><div className="admin-card__head"><div><h2>Perfil de administrador</h2><p>Edita tus datos de contacto sin cambiar tus permisos administrativos.</p></div></div><form className="admin-form" onSubmit={submit}><div className="form-row">{input('fullName','Nombre completo',profile,'full_name')}{input('phone','Teléfono',profile)}</div><div className="form-row">{input('country','País',profile)}{input('city','Ciudad',profile)}</div>{input('emergencyContact','Contacto de emergencia',profile,'emergency_contact')}<div className="admin-form__actions"><span>{message}</span><button className="button button--primary">Guardar perfil</button></div></form></section>}

const pageDefaults:Record<string,Row>={home:{page_key:'home',eyebrow:'Tours auténticos en Panamá',title:'La aventura empieza donde termina la rutina.',description:'Explora volcanes, islas y bosques con guías locales que conocen cada rincón de Chiriquí.',image:'/images/bongo-hero.png',buttons:'[{"label":"Explorar tours","url":"#tours","style":"primary"},{"label":"Diseña tu aventura","url":"/contacto","style":"glass"}]',meta:'["08° 46′ N","Chiriquí, Panamá","Desde 2013"]'},tours:{page_key:'tours',eyebrow:'Explora Panamá',title:'Encuentra tu próxima aventura.',description:'Experiencias pequeñas, guías locales y paisajes que se quedan contigo.',buttons:'[]',meta:'[]'},services:{page_key:'services',eyebrow:'Complementa la aventura',title:'Servicios que hacen el viaje más fácil.',description:'',buttons:'[]',meta:'[]'},lodgings:{page_key:'lodgings',eyebrow:'Descansa bien',title:'Hospedajes con alma de aventura.',description:'Opciones claras por persona o para tu grupo completo.',buttons:'[]',meta:'[]'},blog:{page_key:'blog',eyebrow:'Historias de ruta',title:'El cuaderno de Bongo.',description:'Ideas honestas y consejos locales para viajar mejor por Panamá.',buttons:'[]',meta:'[]'},faqs:{page_key:'faqs',eyebrow:'Centro de ayuda',title:'Preguntas frecuentes.',description:'Todo lo que necesitas saber antes de vivir la aventura.',buttons:'[]',meta:'[]'}};
function parseList(value:unknown,kind:'buttons'|'meta'){try{const rows=JSON.parse(String(value||'[]')) as Array<Record<string,string>>|string[];return kind==='meta'?(rows as string[]).join('\n'):(rows as Array<Record<string,string>>).map(x=>`${x.label}|${x.url}|${x.style||'primary'}`).join('\n')}catch{return ''}}
function AppearanceManager({rows,upload,reload}:{rows:Row[];upload:(file:File)=>Promise<string>;reload:()=>Promise<void>}){const [selected,setSelected]=useState<Row|null>(null);const [status,setStatus]=useState('');const merged=Object.values(pageDefaults).map(base=>rows.find(row=>row.page_key===base.page_key)??base);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setStatus('Guardando…');const data=new FormData(e.currentTarget);let image=String(data.get('image')||'');const file=data.get('coverFile');if(file instanceof File&&file.size)image=await upload(file);const labels=data.getAll('buttonLabel').map(String);const urls=data.getAll('buttonUrl').map(String);const styles=data.getAll('buttonStyle').map(String);const buttons=labels.map((label,index)=>({label,url:urls[index]||'/',style:styles[index]==='glass'?'glass':'primary'})).filter(x=>x.label.trim());const meta=String(data.get('meta')||'').split('\n').map(x=>x.trim()).filter(Boolean);const body={resource:'page',pageKey:data.get('pageKey'),eyebrow:data.get('eyebrow'),title:data.get('title'),description:data.get('description'),image,buttons:JSON.stringify(buttons),meta:JSON.stringify(meta)};const res=await fetch('/api/admin/cms',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});setStatus(res.ok?'Portada actualizada.':'No se pudo guardar.');if(res.ok){setSelected(null);await reload();}}return selected?<section className="admin-card"><button className="admin-back" onClick={()=>setSelected(null)}>← Volver a portadas</button><h2>Editar portada: {String(selected.page_key)}</h2><form className="admin-form" onSubmit={submit}><input type="hidden" name="pageKey" value={String(selected.page_key)}/>{input('eyebrow','Texto superior',selected)}{input('title','Título principal',selected)}<label>Descripción<textarea name="description" rows={4} defaultValue={val(selected,'description')}/></label>{input('image','URL de foto de banner',selected)}<label>O subir foto<input name="coverFile" type="file" accept="image/*"/></label><BannerButtonFields value={selected.buttons}/><label>Datos inferiores, uno por línea<textarea name="meta" rows={4} defaultValue={parseList(selected.meta,'meta')}/></label><div className="admin-form__actions"><span>{status}</span><button className="button button--primary">Guardar portada</button></div></form></section>:<section className="admin-list"><div className="admin-list__head"><div><h2>Portadas y banners</h2><p>Edita foto, texto y cualquier cantidad de botones por página.</p></div></div><div className="admin-content-rows">{merged.map(row=><article key={String(row.page_key)}><div><b>{String(row.title)}</b><small>{String(row.page_key)}</small></div><button onClick={()=>setSelected(row)}>Editar portada →</button></article>)}</div></section>}

function BannerButtonFields({value}:{value:unknown}){let initial:Array<{label:string;url:string;style:string}>=[];try{initial=JSON.parse(String(value||'[]'))}catch{}const [buttons,setButtons]=useState(initial);return <fieldset className="banner-button-editor"><legend>Botones del banner</legend>{buttons.map((button,index)=><div key={index}><input name="buttonLabel" aria-label={`Texto del botón ${index+1}`} value={button.label} onChange={e=>setButtons(old=>old.map((x,i)=>i===index?{...x,label:e.target.value}:x))}/><input name="buttonUrl" aria-label={`Enlace del botón ${index+1}`} value={button.url} onChange={e=>setButtons(old=>old.map((x,i)=>i===index?{...x,url:e.target.value}:x))}/><select name="buttonStyle" aria-label={`Estilo del botón ${index+1}`} value={button.style||'primary'} onChange={e=>setButtons(old=>old.map((x,i)=>i===index?{...x,style:e.target.value}:x))}><option value="primary">Principal</option><option value="glass">Transparente</option></select><button type="button" onClick={()=>setButtons(old=>old.filter((_,i)=>i!==index))}>Eliminar</button></div>)}<button type="button" className="button button--small" onClick={()=>setButtons(old=>[...old,{label:'Nuevo botón',url:'/',style:'primary'}])}>+ Agregar botón</button></fieldset>}

function MenuManager({rows,reload}:{rows:Row[];reload:()=>Promise<void>}){const [selected,setSelected]=useState<Row|null|undefined>(undefined);const [status,setStatus]=useState('');async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget).entries());const res=await fetch('/api/admin/cms',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({resource:'menu',...data,id:selected?.id,openNewTab:data.openNewTab==='on'})});setStatus(res.ok?'Elemento guardado.':'No se pudo guardar.');if(res.ok){setSelected(undefined);await reload();}}async function remove(id:unknown){if(!confirm('¿Eliminar este elemento del menú?'))return;const res=await fetch('/api/admin/cms',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({resource:'menu',id})});if(res.ok)await reload();}return selected!==undefined?<section className="admin-card"><button className="admin-back" onClick={()=>setSelected(undefined)}>← Volver al menú</button><h2>{selected?'Editar':'Agregar'} elemento</h2><form className="admin-form" onSubmit={submit}><div className="form-row">{input('label','Texto',selected??null)}{input('url','Enlace',selected??null)}</div><div className="form-row"><label>Posición<select name="position" defaultValue={val(selected??null,'position')||'main'}><option value="main">Menú principal</option><option value="bongo">Submenú Bongo</option></select></label><label>Orden<input name="sortOrder" type="number" defaultValue={val(selected??null,'sort_order')||'0'}/></label></div><label className="check"><input name="openNewTab" type="checkbox" defaultChecked={Boolean(selected?.open_new_tab)}/> Abrir en otra pestaña</label><div className="admin-form__actions"><span>{status}</span><button className="button button--primary">Guardar elemento</button></div></form></section>:<section className="admin-list"><div className="admin-list__head"><div><h2>Estructura del menú</h2><p>Cambia textos, enlaces, ubicación y orden.</p></div><button className="button button--primary button--small" onClick={()=>setSelected(null)}>+ Agregar item</button></div><div className="admin-content-rows">{rows.map(row=><article key={String(row.id)}><div><b>{String(row.label)}</b><small>{String(row.position)} · orden {String(row.sort_order)} · {String(row.url)}</small></div><div className="admin-row-actions"><button onClick={()=>setSelected(row)}>Editar</button><button className="danger" onClick={()=>remove(row.id)}>Eliminar</button></div></article>)}</div></section>}

const categoryNames:Record<string,string>={tour:'Tours',service:'Servicios',lodging:'Hospedajes',post:'Blog',faq:'FAQs'};
function CategoryManager({groups,reload}:{groups:Record<string,Row[]>;reload:()=>Promise<void>}){const [entity,setEntity]=useState('tour');const [selected,setSelected]=useState<Row|null|undefined>(undefined);const [status,setStatus]=useState('');const builtIns=entity==='tour'?(categories as unknown as Row[]):[];const stored=groups[entity]??[];const list=[...builtIns.filter(x=>!stored.some(y=>String(y.slug)===String(x.slug))),...stored];async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget).entries());const res=await fetch('/api/admin/cms',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({resource:'category',entity,...data,id:selected?.id})});setStatus(res.ok?'Categoría guardada.':'No se pudo guardar.');if(res.ok){setSelected(undefined);await reload();}}async function remove(id:unknown){if(!confirm('¿Eliminar esta categoría? Los contenidos conservarán sus datos, pero quedarán sin categoría.'))return;const res=await fetch('/api/admin/cms',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({resource:'category',entity,id})});if(res.ok)await reload();}return selected!==undefined?<section className="admin-card"><button className="admin-back" onClick={()=>setSelected(undefined)}>← Volver a categorías</button><h2>{selected?'Editar':'Crear'} categoría de {categoryNames[entity]}</h2><form className="admin-form" onSubmit={submit}>{input('name','Nombre',selected??null)}{entity!=='faq'&&input('slug','URL amigable',selected??null)}<label>Descripción<textarea name="description" rows={4} defaultValue={val(selected??null,'description')}/></label><label>Orden<input name="sortOrder" type="number" defaultValue={val(selected??null,'sort_order')||'0'}/></label><div className="admin-form__actions"><span>{status}</span><button className="button button--primary">Guardar categoría</button></div></form></section>:<section className="admin-list"><div className="admin-list__head"><div><h2>Categorías independientes</h2><p>Cada módulo usa su propia clasificación; nunca se mezclan.</p></div><button className="button button--primary button--small" onClick={()=>setSelected(null)}>+ Agregar categoría</button></div><div className="admin-module-tabs">{Object.entries(categoryNames).map(([key,name])=><button className={entity===key?'active':''} key={key} onClick={()=>setEntity(key)}>{name}</button>)}</div><div className="admin-content-rows">{list.map(row=><article key={rowKey(entity,row)}><div><b>{String(row.name)}</b><small>{categoryNames[entity]}</small></div><div className="admin-row-actions"><button onClick={()=>setSelected(row)}>Editar</button>{row.id&&<button className="danger" onClick={()=>remove(row.id)}>Eliminar</button>}</div></article>)}</div></section>}
