'use client';
import { FormEvent,useEffect,useState } from 'react';
import { FaEnvelope,FaLock,FaUser } from 'react-icons/fa6';
import { TurnstileWidget } from './turnstile-widget';

type Mode='login'|'register'|'recover'|'reset';
export function AuthForm({returnTo='/cuenta',turnstileSiteKey}:{returnTo?:string;turnstileSiteKey:string}){
  const [mode,setMode]=useState<Mode>('login');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');const [recoveryToken,setRecoveryToken]=useState('');const [pendingEmail,setPendingEmail]=useState('');const [challengeKey,setChallengeKey]=useState(0);
  useEffect(()=>{const hash=new URLSearchParams(window.location.hash.replace(/^#/,''));const token=hash.get('access_token');if(token&&hash.get('type')==='recovery'){setRecoveryToken(token);setMode('reset');history.replaceState(null,'',window.location.pathname+window.location.search)}},[]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');setMessage('');const data=new FormData(event.currentTarget);const payload=Object.fromEntries(data.entries());let endpoint=`/api/auth/${mode}`;if(mode==='reset'){endpoint='/api/auth/update-password';payload.accessToken=recoveryToken}try{const response=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const result=await response.json() as {ok?:boolean;error?:string;message?:string;confirmed?:boolean;isAdmin?:boolean};if(!response.ok)throw new Error(result.error??'No se pudo completar la solicitud.');setMessage(result.message??'Listo.');if(mode==='register'&&!result.confirmed)setPendingEmail(String(payload.email??''));if(mode==='login'||(mode==='register'&&result.confirmed))window.location.assign(result.isAdmin?'/admin':returnTo);if(mode==='reset')setTimeout(()=>setMode('login'),1000)}catch(cause){setError(cause instanceof Error?cause.message:'No se pudo completar la solicitud.');if(mode!=='reset')setChallengeKey(key=>key+1)}finally{setBusy(false)}}
  async function resend(){const form=document.querySelector<HTMLFormElement>('.auth-card form');const token=form?String(new FormData(form).get('turnstileToken')??''):'';setBusy(true);setError('');try{const response=await fetch('/api/auth/resend',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:pendingEmail,turnstileToken:token})});const result=await response.json() as {message?:string;error?:string};if(!response.ok)throw new Error(result.error??'No se pudo reenviar.');setMessage(result.message??'Correo reenviado.')}catch(cause){setError(cause instanceof Error?cause.message:'No se pudo reenviar.')}finally{setBusy(false);setChallengeKey(key=>key+1)}}
  const title=mode==='register'?'Crear mi cuenta':mode==='recover'?'Recuperar acceso':mode==='reset'?'Nueva contraseña':'Bienvenido de vuelta';
  function changeMode(next:Mode){setMode(next);setMessage('');setError('');setPendingEmail('');setChallengeKey(key=>key+1)}
  return <div className="auth-card"><div className="auth-card__brand"><img src="/images/bongo-logo.png" alt="Bongo Outdoors"/><p className="eyebrow"><span/>Tu próxima aventura</p><h1>{title}</h1><p>{mode==='register'?'Regístrate para administrar reservas, pedidos y tu información.':mode==='recover'?'Te enviaremos un enlace seguro a tu correo.':mode==='reset'?'Crea una contraseña segura para volver a ingresar.':'Accede a tus reservas y preferencias de viaje.'}</p></div><form onSubmit={submit}>
    {mode==='register'&&<label>Nombre completo<div><FaUser/><input name="fullName" autoComplete="name" required/></div></label>}
    {mode!=='reset'&&<label>Correo electrónico<div><FaEnvelope/><input name="email" type="email" autoComplete="email" required/></div></label>}
    {!['recover'].includes(mode)&&<label>{mode==='reset'?'Nueva contraseña':'Contraseña'}<div><FaLock/><input name="password" type="password" autoComplete={mode==='login'?'current-password':'new-password'} minLength={8} required/></div></label>}
    {mode!=='reset'&&turnstileSiteKey&&<TurnstileWidget key={challengeKey} siteKey={turnstileSiteKey} action={mode}/>} 
    <button className="button button--primary full" disabled={busy}>{busy?'Procesando…':mode==='register'?'Crear cuenta':mode==='recover'?'Enviar enlace':mode==='reset'?'Actualizar contraseña':'Iniciar sesión'} <b>→</b></button>
    {message&&<p className="auth-message" role="status">{message}</p>}{pendingEmail&&<button className="auth-resend" type="button" onClick={resend} disabled={busy}>Reenviar correo de confirmación</button>}{error&&<p className="auth-error" role="alert">{error}</p>}
    <div className="auth-switch">{mode==='login'&&<><button type="button" onClick={()=>changeMode('recover')}>¿Olvidaste tu contraseña?</button><span>¿No tienes cuenta? <button type="button" onClick={()=>changeMode('register')}>Regístrate</button></span></>}{mode!=='login'&&<button type="button" onClick={()=>changeMode('login')}>← Volver a iniciar sesión</button>}</div>
  </form></div>;
}
