import { env } from 'cloudflare:workers';
export async function ensureDatabase(){const db=env.DB;const statements=[
`CREATE TABLE IF NOT EXISTS categories (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,slug TEXT NOT NULL UNIQUE,description TEXT,created_at TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS policies (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,content TEXT NOT NULL,is_global INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS tours (id INTEGER PRIMARY KEY AUTOINCREMENT,slug TEXT NOT NULL UNIQUE,name TEXT NOT NULL,h1 TEXT NOT NULL,meta_description TEXT,keywords TEXT,description TEXT NOT NULL,location TEXT NOT NULL,meeting_point TEXT,departure_time TEXT,duration TEXT NOT NULL,difficulty TEXT NOT NULL,capacity TEXT,category_id INTEGER,price_type TEXT NOT NULL DEFAULT 'person',person_price REAL,group_price REAL,season_prices TEXT,includes TEXT,not_included TEXT,bring TEXT,prohibited TEXT,recommendations TEXT,extra_messages TEXT,gallery TEXT,cover_image TEXT,policy_id INTEGER,status TEXT NOT NULL DEFAULT 'draft',created_at TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS services (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,slug TEXT NOT NULL UNIQUE,description TEXT NOT NULL,price_type TEXT NOT NULL,price REAL NOT NULL,image TEXT,active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS lodgings (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,slug TEXT NOT NULL UNIQUE,location TEXT NOT NULL,description TEXT NOT NULL,price_type TEXT NOT NULL,person_price REAL,group_price REAL,image TEXT,active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS posts (id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,slug TEXT NOT NULL UNIQUE,excerpt TEXT NOT NULL,content TEXT NOT NULL,cover_image TEXT,status TEXT NOT NULL DEFAULT 'draft',published_at TEXT,created_at TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS faq_categories (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,sort_order INTEGER NOT NULL DEFAULT 0)`,
`CREATE TABLE IF NOT EXISTS faqs (id INTEGER PRIMARY KEY AUTOINCREMENT,category_id INTEGER,question TEXT NOT NULL,answer TEXT NOT NULL,sort_order INTEGER NOT NULL DEFAULT 0,active INTEGER NOT NULL DEFAULT 1)`,
`CREATE TABLE IF NOT EXISTS bookings (id INTEGER PRIMARY KEY AUTOINCREMENT,reference TEXT NOT NULL UNIQUE,user_id TEXT,tour_slug TEXT NOT NULL,customer_name TEXT NOT NULL,email TEXT NOT NULL,phone TEXT NOT NULL,tour_date TEXT NOT NULL,quantity INTEGER NOT NULL,price_mode TEXT NOT NULL,total REAL NOT NULL,payment_method TEXT NOT NULL DEFAULT 'cash',status TEXT NOT NULL DEFAULT 'pending',created_at TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS reviews (id INTEGER PRIMARY KEY AUTOINCREMENT,tour_slug TEXT NOT NULL,user_id TEXT,name TEXT NOT NULL,rating INTEGER NOT NULL,comment TEXT NOT NULL,approved INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS user_profiles (user_id TEXT PRIMARY KEY,email TEXT NOT NULL,full_name TEXT,phone TEXT,country TEXT,city TEXT,emergency_contact TEXT,marketing_opt_in INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS service_categories (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,slug TEXT NOT NULL UNIQUE,description TEXT,sort_order INTEGER NOT NULL DEFAULT 0,active INTEGER NOT NULL DEFAULT 1)`,
`CREATE TABLE IF NOT EXISTS lodging_categories (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,slug TEXT NOT NULL UNIQUE,description TEXT,sort_order INTEGER NOT NULL DEFAULT 0,active INTEGER NOT NULL DEFAULT 1)`,
`CREATE TABLE IF NOT EXISTS post_categories (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,slug TEXT NOT NULL UNIQUE,description TEXT,sort_order INTEGER NOT NULL DEFAULT 0,active INTEGER NOT NULL DEFAULT 1)`,
`CREATE TABLE IF NOT EXISTS site_pages (id INTEGER PRIMARY KEY AUTOINCREMENT,page_key TEXT NOT NULL UNIQUE,eyebrow TEXT,title TEXT NOT NULL,description TEXT,image TEXT,buttons TEXT NOT NULL DEFAULT '[]',meta TEXT NOT NULL DEFAULT '[]',updated_at TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS menu_items (id INTEGER PRIMARY KEY AUTOINCREMENT,parent_id INTEGER,label TEXT NOT NULL,url TEXT NOT NULL,position TEXT NOT NULL DEFAULT 'main',sort_order INTEGER NOT NULL DEFAULT 0,active INTEGER NOT NULL DEFAULT 1,open_new_tab INTEGER NOT NULL DEFAULT 0)`,
`CREATE INDEX IF NOT EXISTS idx_tours_status ON tours(status)`,`CREATE INDEX IF NOT EXISTS idx_bookings_user_id ON bookings(user_id)`,`CREATE INDEX IF NOT EXISTS idx_reviews_tour_approved ON reviews(tour_slug,approved)`,`CREATE INDEX IF NOT EXISTS idx_menu_position_sort ON menu_items(position,sort_order)`];await db.batch(statements.map(sql=>db.prepare(sql)));for(const sql of [`ALTER TABLE tours ADD COLUMN departure_time TEXT`,`ALTER TABLE tours ADD COLUMN not_included TEXT`,`ALTER TABLE tours ADD COLUMN recommendations TEXT`,`ALTER TABLE tours ADD COLUMN extra_messages TEXT`,`ALTER TABLE services ADD COLUMN category_id INTEGER`,`ALTER TABLE lodgings ADD COLUMN category_id INTEGER`,`ALTER TABLE posts ADD COLUMN category_id INTEGER`]){try{await db.prepare(sql).run()}catch{/* La columna ya existe. */}}const menuCount=await db.prepare('SELECT COUNT(*) AS total FROM menu_items').first<{total:number}>();if(!menuCount?.total){const menu=[['Inicio','/','main',0],['Bongo','#','main',1],['Blog','/blog','main',2],['FAQs','/faqs','main',3],['Contacto','/contacto','main',4],['Tours','/tours','bongo',0],['Bike tours','/tours?categoria=bike','bongo',1],['Shuttle Panamá','/servicios/shuttle-panama','bongo',2],['Servicio de drones','/servicios/fotografia-drones','bongo',3],['Tours en Pedasí','/tours?destino=pedasi','bongo',4],['Hospedaje y cabañas','/hospedajes','bongo',5],['Responsabilidad social','/responsabilidad-social','bongo',6],['Derechos de autor','/derechos-de-autor','bongo',7]];await db.batch(menu.map(item=>db.prepare('INSERT INTO menu_items (label,url,position,sort_order,active,open_new_tab) VALUES (?,?,?,?,1,0)').bind(...item)));}return db;}
export function slugify(value:string){return value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');}
