import { NextResponse } from 'next/server';
import { getChatGPTUser,isAdminEmail } from '../../chatgpt-auth';
import { notifyBookingStatus,notifyNewBooking } from '../../lib/email';
import { ensureDatabase } from '../../../db/runtime';

type BookingRow={reference:string;customer_name:string;email:string;phone:string;tour_slug:string;tour_date:string;quantity:number;price_mode:string;total:number;status:string;payment_method:string;admin_notes?:string|null};
const allowedStatuses=['pending','confirmed','completed','cancelled','cancellation_requested'];
export async function POST(request:Request){const body=await request.json() as Record<string,unknown>;const required=['tourSlug','customerName','email','phone','tourDate','quantity','priceMode','total'];if(required.some(key=>!body[key]))return NextResponse.json({error:'Completa todos los campos.'},{status:400});const db=await ensureDatabase();const user=await getChatGPTUser();const now=new Date().toISOString();const email=String(body.email??'').trim().toLowerCase();if(!user){const existing=await db.prepare('SELECT user_id FROM user_profiles WHERE email=? AND deleted_at IS NULL LIMIT 1').bind(email).first();if(existing)return NextResponse.json({error:'Este correo ya tiene una cuenta. Inicia sesión para continuar con tu pedido.'},{status:409});}const reference=`BO-${Date.now().toString(36).toUpperCase()}-${crypto.randomUUID().slice(0,4).toUpperCase()}`;await db.prepare(`INSERT INTO bookings (reference,user_id,tour_slug,customer_name,email,phone,tour_date,quantity,price_mode,total,payment_method,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,'cash','pending',?,?)`).bind(reference,user?.userId??null,String(body.tourSlug),String(body.customerName),String(body.email),String(body.phone),String(body.tourDate),Number(body.quantity),String(body.priceMode),Number(body.total),now,now).run();await db.prepare(`INSERT INTO booking_status_history (booking_reference,status,note,changed_by,created_at) VALUES (?,'pending','Pedido creado',?,?)`).bind(reference,user?.email??String(body.email),now).run();const order=await db.prepare('SELECT * FROM bookings WHERE reference=?').bind(reference).first<BookingRow>();if(order)await notifyNewBooking(db,order);return NextResponse.json({ok:true,reference,order,message:'Reserva recibida. El pago será contra entrega en efectivo.'});}

async function requireAdmin(){const user=await getChatGPTUser();if(!user||!isAdminEmail(user.email))return null;return user;}
export async function GET(request:Request){if(!await requireAdmin())return NextResponse.json({error:'Acceso de administrador requerido.'},{status:403});const db=await ensureDatabase();const reference=new URL(request.url).searchParams.get('reference');if(reference){const [order,history]=await Promise.all([db.prepare('SELECT * FROM bookings WHERE reference=?').bind(reference).first(),db.prepare('SELECT * FROM booking_status_history WHERE booking_reference=? ORDER BY id DESC').bind(reference).all()]);return NextResponse.json({order,history:history.results});}const result=await db.prepare('SELECT * FROM bookings ORDER BY id DESC LIMIT 300').all();return NextResponse.json(result.results);}
export async function PATCH(request:Request){const body=await request.json() as Record<string,unknown>;const current=await getChatGPTUser();if(!current)return NextResponse.json({error:'Inicia sesión.'},{status:401});const db=await ensureDatabase();if(body.action==='request_cancel'){const now=new Date().toISOString();await db.prepare(`UPDATE bookings SET status='cancellation_requested',updated_at=? WHERE reference=? AND user_id=? AND status IN ('pending','confirmed')`).bind(now,String(body.reference??''),current.userId).run();await db.prepare(`INSERT INTO booking_status_history (booking_reference,status,note,changed_by,created_at) VALUES (?,'cancellation_requested','Solicitud del cliente',?,?)`).bind(String(body.reference??''),current.email,now).run();const order=await db.prepare('SELECT * FROM bookings WHERE reference=?').bind(String(body.reference??'')).first<BookingRow>();if(order)await notifyBookingStatus(db,order);return NextResponse.json({ok:true});}if(!isAdminEmail(current.email))return NextResponse.json({error:'Acceso de administrador requerido.'},{status:403});if(body.action==='mark_seen'){await db.prepare('UPDATE bookings SET seen=1 WHERE reference=?').bind(String(body.reference??'')).run();return NextResponse.json({ok:true});}const status=String(body.status??'');if(!allowedStatuses.includes(status))return NextResponse.json({error:'Estado inválido.'},{status:400});const reference=String(body.reference??'');const previous=await db.prepare('SELECT * FROM bookings WHERE reference=?').bind(reference).first<BookingRow>();if(!previous)return NextResponse.json({error:'Pedido no encontrado.'},{status:404});const now=new Date().toISOString();const customerName=String(body.customerName??previous.customer_name).trim();const email=String(body.email??previous.email).trim().toLowerCase();const phone=String(body.phone??previous.phone).trim();const tourDate=String(body.tourDate??previous.tour_date);const quantity=Math.max(1,Number(body.quantity??previous.quantity));const total=Math.max(0,Number(body.total??previous.total));const adminNotes=String(body.adminNotes??previous.admin_notes??'').slice(0,2000);await db.prepare('UPDATE bookings SET customer_name=?,email=?,phone=?,tour_date=?,quantity=?,total=?,status=?,admin_notes=?,updated_at=? WHERE reference=?').bind(customerName,email,phone,tourDate,quantity,total,status,adminNotes,now,reference).run();if(status!==previous.status||String(body.statusNote??'').trim())await db.prepare('INSERT INTO booking_status_history (booking_reference,status,note,changed_by,created_at) VALUES (?,?,?,?,?)').bind(reference,status,String(body.statusNote??'Actualización administrativa').slice(0,500),current.email,now).run();const order=await db.prepare('SELECT * FROM bookings WHERE reference=?').bind(reference).first<BookingRow>();if(order&&status!==previous.status)await notifyBookingStatus(db,order);return NextResponse.json({ok:true,order});}
